export const dataThemes = [
  {
    id: 'default',
    name: 'Default Emerald',
    description: 'Clean and modern emerald theme',
    category: 'Modern',
    isFavorite: true,
    isDefault: true,
    createdAt: '2024-01-01',
    theme: {
      primaryColor: '#059669',
      secondaryColor: '#10b981',
      accentColor: '#34d399',
      backgroundColor: '#ffffff',
      textColor: '#374151',
      fontFamily: 'Inter',
      fontSize: 16,
      borderRadius: 8,
      darkMode: false,
      layout: 'modern',
      headerHeight: 80,
      sidebarWidth: 280,
      contentPadding: 24,
      cardShadow: 'medium',
      buttonStyle: 'rounded',
      navigationStyle: 'sidebar',
      logoPosition: 'left',
      animations: true,
      highContrast: false,
      reducedMotion: false,
      customCSS: '',
      favicon: '',
      logoUrl: ''
    }
  },
  {
    id: 'elegant-dark',
    name: 'Elegant Dark',
    description: 'Sophisticated dark theme with gold accents',
    category: 'Elegant',
    isFavorite: false,
    isDefault: false,
    createdAt: '2024-01-02',
    theme: {
      primaryColor: '#1f2937',
      secondaryColor: '#374151',
      accentColor: '#fbbf24',
      backgroundColor: '#111827',
      textColor: '#f9fafb',
      fontFamily: 'Montserrat',
      fontSize: 16,
      borderRadius: 12,
      darkMode: true,
      layout: 'elegant',
      headerHeight: 90,
      sidebarWidth: 300,
      contentPadding: 32,
      cardShadow: 'large',
      buttonStyle: 'rounded',
      navigationStyle: 'sidebar',
      logoPosition: 'center',
      animations: true,
      highContrast: false,
      reducedMotion: false,
      customCSS: '',
      favicon: '',
      logoUrl: ''
    }
  },
  {
    id: 'warm-casual',
    name: 'Warm Casual',
    description: 'Friendly orange theme perfect for casual dining',
    category: 'Casual',
    isFavorite: true,
    isDefault: false,
    createdAt: '2024-01-03',
    theme: {
      primaryColor: '#ea580c',
      secondaryColor: '#f97316',
      accentColor: '#fb923c',
      backgroundColor: '#fefbf3',
      textColor: '#431407',
      fontFamily: 'Poppins',
      fontSize: 15,
      borderRadius: 16,
      darkMode: false,
      layout: 'casual',
      headerHeight: 75,
      sidebarWidth: 260,
      contentPadding: 20,
      cardShadow: 'small',
      buttonStyle: 'pill',
      navigationStyle: 'topbar',
      logoPosition: 'left',
      animations: true,
      highContrast: false,
      reducedMotion: false,
      customCSS: '',
      favicon: '',
      logoUrl: ''
    }
  },
  {
    id: 'classic-blue',
    name: 'Classic Blue',
    description: 'Traditional blue theme with timeless appeal',
    category: 'Classic',
    isFavorite: false,
    isDefault: false,
    createdAt: '2024-01-04',
    theme: {
      primaryColor: '#1e40af',
      secondaryColor: '#3b82f6',
      accentColor: '#60a5fa',
      backgroundColor: '#ffffff',
      textColor: '#1e293b',
      fontFamily: 'Roboto',
      fontSize: 16,
      borderRadius: 6,
      darkMode: false,
      layout: 'classic',
      headerHeight: 85,
      sidebarWidth: 280,
      contentPadding: 24,
      cardShadow: 'medium',
      buttonStyle: 'square',
      navigationStyle: 'sidebar',
      logoPosition: 'left',
      animations: false,
      highContrast: false,
      reducedMotion: true,
      customCSS: '',
      favicon: '',
      logoUrl: ''
    }
  }
];
