const tags: Record<string, string> = {
  "gioi-thieu": "Giới thiệu",
  "gio-hang": "Giỏ hàng",
  "thong-tin": "Thông tin cá nhân",
  "thuc-don": "Thực đơn",
  "goi-mon": "Gọi món",
  "khuyen-mai": "Khuyến mãi",
  "lien-he": "Liên hệ",
  "goi-mon-nhanh": "Mua nhanh",
  "thanh-toan": "Thanh toán",
  "tin-tuc": "Tin tức",
  "chinh-sach": "Chính sách",
  "dang-nhap": "Đăng nhập",
  "dang-ki": "Đăng kí",
  "san-pham": "Sản phẩm",
  "yeu-thich": "Yêu thích",
  "danh-gia": "Đánh giá",
  "tim-kiem": "Tìm kiếm",
  "vnpay-payment-result": "Thông tin thanh toán",
  "thit-tuoi": "Thịt tươi",
  "san-pham-moi": "Sản phẩm mới",
  "san-pham-hot": "Sản phẩm nổi bật",
  "san-pham-giam-gia": "Sản phẩm giảm giá",
  "san-pham-ban-chay": "Sản phẩm bán chạy",
  "thuc-uong": "Thức uống",
  "don-hang-cua-toi": "Đơn hàng của tôi",
  "price-asc": "Giá từ thấp đến cao",
  "price-desc": "Giá từ cao đến thấp",
  "name-asc": "Tên A-Z",
  "name-desc": "Tên Z-A",
  "new": "Mới nhất",
  "old": "Cũ nhất",
  "best-seller": "Bán chạy",
  "com-tam-suon-bi-cha": "Cơm tấm sườn bì chả",
  "mon-chinh": "Món chính",
  "mon-chay": "Món chay",
  "com": "Cơm",
  "thanh-toan-vnpay": "Thanh toán VnPay",
  "do-uong": "Đồ uống",
  "an-vat-trang-mieng": "Ăn vặt & tráng miệng",
  "mon-nuoc": "Món nước",
  "ca-phe": "Cà Phê",
  "nuoc-giai-khat": "Nước giải khát",
  "tra-sua": "Trà Sữa",
  "banh-trang": "Bánh tráng",
  "banh-man": "Bánh Mặn",
  "banh-ngot": "Bánh Ngọt",
  "thit-bo": "Thịt Bò",
  "thit-ga": "Thịt Gà",
  "thit-heo": "Thịt Heo",
  "tom": "Tôm",
  "muc": "Mực",
  "ca-cac-loai": "Cá các loại",
  "cac-loai-oc": "Các loại ốc",
  "cu-cai-trang": "Củ cải trắng",
  "ca-rot": "Cà rốt",
  "cai-thia": "Cải thìa",
  "bong-cai": "Bông cải",
  "nam-meo": "Nấm mèo",
  "nam-kim-cham": "Nấm kim châm",
  "nam-moc-nhi": "Nấm mộc nhỉ",
  "nam-dui-ga": "Nấm đùi gà",
  "dau-hu-tuoi": "Đậu hủ tươi",
  "dau-hu-chien": "Đậu hủ chiên",
  "dau-hu-ki": "Đậu hủ ki",
  "cha-chay": "Chả chay",
  "dua-leo": "Dưa leo",
  "ca-chua": "Cà chua",
  "gia-do": "Giá đỗ",
  "rau-xa-lach": "Rau xà lách",
  "rau-ma": "Rau má",
  "hoa-chuoi-bap-chuoi": "Hoa chuối (bắp chuối)",
  "rau-thom-hung-que-hung-lang": "Rau thơm húng quế - húng láng",
  "rau-muong": "Rau muống",
  "hanh-tay": "Hành tây",
  "ngo-gai": "Ngò gai",
  "hanh-la": "Hành lá",
  "danh-muc-123": "Danh mục 123",
  "soda": "Soda ",
  "thit-vit": "Thịt Vịt",
  "suon-non": "Sườn Non",
  "tom-su": "Tôm Sú",
  "cua-bien": "Cua Biển",
  "ca": "Cá",
  "muc-ong": "Mực Ống",
  "so": "Sò ",
  "mi": "Mì ",
  "chao": "Cháo ",
  "nuoc-ep": "Nước Ép",
  "sinh-to": "Sinh Tố ",
  "com-chay": "Cơm Chay",
  "bun-chay": "Bún Chay",
  "lau-chay": "Lẩu Chay",
  "mon-xao-chay": "Món Xào Chay",
  "canh-chay": "Canh Chay",
  "che": "Chè ",
  "kem": "Kem",
  "sua-chua": "Sữa Chua",
  "trai-cay-dia": "Trái Cây Dĩa",
  "bun-bo-hue": "Bún bò Huế",
  "ca-phe-sua-da": "Cà phê sữa đá",
  "bun-cha-ha-noi": "Bún chả Hà Nội",
  "canh-chua-chay": "Canh chua chay",
  "tra-sua-tran-chau": "Trà sữa trân châu",
  "nuoc-ep-cam-tuoi": "Nước ép cam tươi",
  "banh-trang-cha-bong": "Bánh tráng chà bông",
  "banh-da-lon": "Bánh da lợn",
  "banh-khoai-mo-chien": "Bánh khoai mỡ chiên",
  "banh-trang-tac": "Bánh tráng tắc",
  "chao-ga-xe-phay": "Cháo gà xé phay",
  "nem-nuong": "Nem nướng",
  "snack-bim-bim": "Snack (Bim bim)",
  "keo-ngot": "Kẹo ngọt",
  "rau-cau": "Rau câu",
  "nguyen-thuy-linh": "Nguyễn Thùy Linh",
  "nguyen-thi-meo-meo": "Nguyễn Thị Mèo Meo"
};

export default tags;