const tags: Record<string, string> = {
  'gioi-thieu': 'Giới thiệu',
  'gio-hang': 'Giỏ hàng',
  'thong-tin': 'Thông tin cá nhân',
  'thuc-don': 'Thực đơn',
  'goi-mon': 'Gọi món',
  'khuyen-mai': 'Khuyến mãi',
  'lien-he': 'Liên hệ',
  'goi-mon-nhanh': 'Mua nhanh',
  'thanh-toan': 'Thanh toán',
  'tin-tuc': 'Tin tức',
  'chinh-sach': 'Chính sách',
  'dang-nhap': 'Đăng nhập',
  'dang-ky': 'Đăng ký',
  password: 'Mật khẩu',
  'change-password': 'Đổi mật khâu',
  'forgot-password': 'Quên mật khẩu',
  'san-pham': 'Sản phẩm',
  'yeu-thich': 'Yêu thích',
  'danh-gia': 'Đánh giá',
  'tim-kiem': 'Tìm kiếm',
  'vnpay-payment-result': 'Thông tin thanh toán',
  'thit-tuoi': 'Thịt tươi',
  'san-pham-moi': 'Sản phẩm mới',
  'san-pham-hot': 'Sản phẩm nổi bật',
  'san-pham-giam-gia': 'Sản phẩm giảm giá',
  'san-pham-ban-chay': 'Sản phẩm bán chạy',
  'thuc-uong': 'Thức uống',
  'don-hang-cua-toi': 'Đơn hàng của tôi',
  'price-asc': 'Giá từ thấp đến cao',
  'price-desc': 'Giá từ cao đến thấp',
  'name-asc': 'Tên A-Z',
  'name-desc': 'Tên Z-A',
  'updatedAt-desc': 'Mới nhất',
  'rating-desc': 'Đánh giá cao',
  'soldQuantity-desc': 'Bán chạy',
  'best-seller': 'Bán chạy',
  'com-tam-suon-bi-cha': 'Cơm tấm sườn bì chả',
  'mon-chinh': 'Món chính',
  'mon-chay': 'Món chay',
  'cac-loai-com': 'Các loại cơm',
  'thanh-toan-vnpay': 'Thanh toán VnPay',
  'do-uong': 'Đồ uống',
  'an-vat-trang-mieng': 'Ăn vặt & tráng miệng',
  'mon-co-sup': 'Món có súp',
  'ca-phe': 'Cà Phê',
  'nuoc-giai-khat': 'Nước giải khát',
  'tra-sua': 'Trà Sữa',
  'banh-trang': 'Bánh tráng',
  'banh-man': 'Bánh Mặn',
  'banh-ngot': 'Bánh Ngọt',
  'thit-bo': 'Thịt Bò',
  'thit-ga': 'Thịt Gà',
  'thit-heo': 'Thịt Heo',
  tom: 'Tôm',
  muc: 'Mực',
  'ca-cac-loai': 'Cá các loại',
  'cac-loai-oc': 'Các loại ốc',
  'cu-cai-trang': 'Củ cải trắng',
  'ca-rot': 'Cà rốt',
  'cai-thia': 'Cải thìa',
  'bong-cai': 'Bông cải',
  'nam-meo': 'Nấm mèo',
  'nam-kim-cham': 'Nấm kim châm',
  'nam-moc-nhi': 'Nấm mộc nhỉ',
  'nam-dui-ga': 'Nấm đùi gà',
  'dau-hu-tuoi': 'Đậu hủ tươi',
  'dau-hu-chien': 'Đậu hủ chiên',
  'dau-hu-ki': 'Đậu hủ ki',
  'cha-chay': 'Chả chay',
  'dua-leo': 'Dưa leo',
  'ca-chua': 'Cà chua',
  'gia-do': 'Giá đỗ',
  'rau-xa-lach': 'Rau xà lách',
  'rau-ma': 'Rau má',
  'hoa-chuoi-bap-chuoi': 'Hoa chuối (bắp chuối)',
  'rau-thom-hung-que-hung-lang': 'Rau thơm húng quế - húng láng',
  'rau-muong': 'Rau muống',
  'hanh-tay': 'Hành tây',
  'ngo-gai': 'Ngò gai',
  'hanh-la': 'Hành lá',
  'danh-muc-123': 'Danh mục 123',
  soda: 'Soda ',
  'thit-vit': 'Thịt Vịt',
  'suon-non': 'Sườn Non',
  'tom-su': 'Tôm Sú',
  'cua-bien': 'Cua Biển',
  ca: 'Cá',
  'muc-ong': 'Mực Ống',
  so: 'Sò ',
  mi: 'Mì ',
  chao: 'Cháo ',
  'nuoc-ep': 'Nước Ép',
  'sinh-to': 'Sinh Tố ',
  'com-chay': 'Cơm Chay',
  'bun-chay': 'Bún Chay',
  'lau-chay': 'Lẩu Chay',
  'mon-xao-chay': 'Món Xào Chay',
  'canh-chay': 'Canh Chay',
  che: 'Chè ',
  kem: 'Kem',
  'sua-chua': 'Sữa Chua',
  'trai-cay': 'Trái Cây',
  'bun-bo-hue': 'Bún bò Huế',
  'ca-phe-sua-da': 'Cà phê sữa đá',
  'bun-cha-ha-noi': 'Bún chả Hà Nội',
  'canh-chua-chay': 'Canh chua chay',
  'tra-sua-tran-chau': 'Trà sữa trân châu',
  'nuoc-ep-cam-tuoi': 'Nước ép cam tươi',
  'banh-trang-cha-bong': 'Bánh tráng chà bông',
  'banh-da-lon': 'Bánh da lợn',
  'banh-khoai-mo-chien': 'Bánh khoai mỡ chiên',
  'banh-trang-tac': 'Bánh tráng tắc',
  'chao-ga-xe-phay': 'Cháo gà xé phay',
  'nem-nuong': 'Nem nướng',
  'snack-bim-bim': 'Snack (Bim bim)',
  'keo-ngot': 'Kẹo ngọt',
  'rau-cau': 'Rau câu',
  'nguyen-thuy-linh': 'Nguyễn Thùy Linh',
  'nguyen-thi-meo-meo': 'Nguyễn Thị Mèo Meo',
  'com-com': 'Cơm cớm',
  'banh-cuon': 'Bánh cuốn',
  'sua-chua-trai-cay': 'Sữa chua trái cây',
  'xoi-xoai': 'Xôi xoài',
  'xoi-ngot-la-dua': 'Xôi ngọt lá dứa',
  'cha-gio-chien': 'Chả giò chiên',
  'bun-bo-chay': 'Bún bò chay',
  'com-rang-dua-chuot': 'Cơm rang dưa chuột',
  'bun-mam-chay': 'Bún mắm chay',
  'thit-ngong': 'Thịt ngỗng',
  'bo-dau-phong': 'Bơ đậu phộng',
  'mon-nuong': 'Món nướng',
  'ga-nuong-mat-ong': 'Gà nướng mật ong',
  'ca-nuong-trui-mien-tay': 'Cá nướng trui miền Tây',
  'bo-nuong-la-lot': 'Bò nướng lá lốt',
  'suon-nuong-sa-ot': 'Sườn nướng sả ớt',
  'sup-ga-ngo-non-bac-bo': 'Súp gà ngô non Bắc Bộ',
  'sup-ca-hoi-rau-cu': 'Súp cá hồi rau củ',
  'sup-bap-bo-hue': 'Súp bắp bò Huế',
  'sup-nam-hai-san': 'Súp nấm hải sản',
  'xien-que-do-chien': 'Xiên Que & Đồ Chiên',
  'com-tam-chay': 'Cơm Tấm Chay',
  'com-chien-duong-chau-chay': 'Cơm Chiên Dương Châu Chay',
  'com-sen-bach-diep': 'Cơm Sen Bách Diệp',
  'com-dui-ga-chay': 'Cơm Đùi Gà Chay',
  'com-tron-han-quoc-chay': 'Cơm Trộn Hàn Quốc Chay',
  'com-nieu-rau-cu': 'Cơm Niêu Rau Củ',
  'com-chay-kho-quet-chay': 'Cơm Cháy Kho Quẹt Chay',
  'com-lam-thit-nuong-chay': 'Cơm Lam Thịt Nướng Chay',
  'com-ga-hai-nam-chay': 'Cơm Gà Hải Nam Chay',
  'com-cuon-rong-bien-chay': 'Cơm Cuộn Rong Biển Chay',
  'bun-bo-hue-chay': 'Bún Bò Huế Chay',
  'bun-rieu-chay': 'Bún Riêu Chay',
  'bun-cha-gio-chay': 'Bún Chả Giò Chay',
  'bun-thang-chay': 'Bún Thang Chay',
  'bun-moc-chay': 'Bún Mọc Chay',
  'bun-thit-nuong-chay': 'Bún Thịt Nướng Chay',
  'bun-thai-chay': 'Bún Thái Chay',
  'bun-ca-chay': 'Bún Cá Chay',
  'bun-xao-nghe-chay': 'Bún Xào Nghệ Chay',
  'lau-nam-thien-nhien': 'Lẩu Nấm Thiên Nhiên',
  'lau-thai-chua-cay-chay': 'Lẩu Thái Chua Cay Chay',
  'lau-chao-do-chay': 'Lẩu Chao Đỏ Chay',
  'lau-tieu-xanh-chay': 'Lẩu Tiêu Xanh Chay',
  'lau-rieu-cua-dong-chay': 'Lẩu Riêu Cua Đồng Chay',
  'lau-kho-qua-rung-chay': 'Lẩu Khổ Qua Rừng Chay',
  'lau-mam-chay-nam-bo': 'Lẩu Mắm Chay Nam Bộ',
  'lau-kim-chi-chay': 'Lẩu Kim Chi Chay',
  'lau-an-nhien': 'Lẩu An Nhiên',
  'lau-tha-phan-thiet-chay': 'Lẩu Thả Phan Thiết Chay',
  'rau-cu-thap-cam-xao': 'Rau Củ Thập Cẩm Xào',
  'nam-bao-ngu-xao-sa-ot': 'Nấm Bào Ngư Xào Sả Ớt',
  'dau-hu-xao-rau-cu': 'Đậu Hũ Xào Rau Củ',
  'kho-qua-xao-dau-hu': 'Khổ Qua Xào Đậu Hũ',
  'mi-can-xao-chua-ngot': 'Mì Căn Xào Chua Ngọt',
  'bong-cai-xao-nam-huong': 'Bông Cải Xào Nấm Hương',
  'dau-que-xao-jambon-chay': 'Đậu Que Xào Jambon Chay',
  'hu-tieu-xao-chay': 'Hủ Tiếu Xào Chay',
  'gia-do-xao-dau-hu-ki': 'Giá Đỗ Xào Đậu Hũ Ki',
  'mang-tay-xao-toi-chay': 'Măng Tây Xào Tỏi Chay',
  'canh-chua-nam-bo-chay': 'Canh Chua Nam Bộ Chay',
  'canh-kho-qua-rung': 'Canh Khổ Qua Rừng',
  'canh-rau-cu-thap-cam': 'Canh Rau Củ Thập Cẩm',
  'canh-rong-bien-dau-hu': 'Canh Rong Biển Đậu Hũ',
  'canh-nam-hat-sen': 'Canh Nấm Hạt Sen',
  'canh-chua-cay-kieu-thai': 'Canh Chua Cay Kiểu Thái',
  'canh-kiem-mien-tay': 'Canh Kiểm Miền Tây',
  'canh-bau-nau-tom-chay': 'Canh Bầu Nấu Tôm Chay',
  'canh-kim-chi-dau-hu-non': 'Canh Kim Chi Đậu Hũ Non',
  'canh-kho-qua-mo-tim': 'Canh Khoai Mỡ Tím',
  'che-thai-sau-rieng': 'Chè Thái Sầu Riêng',
  'che-buoi-an-giang': 'Chè Bưởi An Giang',
  'che-duong-nhan': 'Chè Dưỡng Nhan',
  'che-khuc-bach-chay': 'Chè Khúc Bạch Chay',
  'che-troi-nuoc-ngu-sac': 'Chè Trôi Nước Ngũ Sắc',
  'che-thach-nhan-sen': 'Chè Thạch Nhãn Sen',
  'che-khoai-deo-dai-loan': 'Chè Khoai Dẻo Đài Loan',
  'che-dau-ngu-cung-dinh': 'Chè Đậu Ngự Cung Đình',
  'che-chuoi-chung': 'Chè Chuối Chưng',
  'che-sam-bo-luong': 'Chè Sâm Bổ Lượng',
  'banh-mousse-chanh-leo-chay': 'Bánh Mousse Chanh Leo Chay',
  'banh-tiramisu-chay': 'Bánh Tiramisu Chay',
  'banh-brownie-socola-hanh-nhan': 'Bánh Brownie Socola Hạnh Nhân',
  'banh-su-kem-chay': 'Bánh Su Kem Chay',
  'banh-bong-lan-cuon-mut-dau': 'Bánh Bông Lan Cuộn Mứt Dâu',
  'banh-tart-trai-cay-chay': 'Bánh Tart Trái Cây Chay',
  'banh-carrot-cake': 'Bánh Cà Rốt Chay',
  'banh-donut-duong-chay': 'Bánh Donut Đường Chay',
  'banh-crepe-sau-rieng-chay': 'Bánh Crepe Sầu Riêng Chay',
  'banh-mi-hoa-cuc-chay': 'Bánh Mì Hoa Cúc Chay',
  'com-ga-xoi-mo': 'Cơm Gà Xối Mỡ',
  'com-suon-nuong-bbq': 'Cơm Sườn Nướng BBQ',
  'com-bo-luc-lac': 'Cơm Bò Lúc Lắc',
  'com-chien-hai-san': 'Cơm Chiên Hải Sản',
  'com-ca-kho-to': 'Cơm Cá Kho Tộ',
  'com-thit-kho-trung': 'Cơm Thịt Kho Trứng',
  'com-dui-vit-quay': 'Cơm Đùi Vịt Quay',
  'com-xa-xiu-quang-dong': 'Cơm Xá Xíu Quảng Đông',
  'com-muc-nhoi-thit-chien': 'Cơm Mực Nhồi Thịt Chiên',
  'mi-quang-ga-ta': 'Mì Quảng Gà Ta',
  'mi-vit-tiem': 'Mì Vịt Tiềm',
  'mi-hoanh-thanh-xa-xiu': 'Mì Hoành Thánh Xá Xíu',
  'mi-xao-gion-hai-san': 'Mì Xào Giòn Hải Sản',
  'mi-cay-hai-san': 'Mì Cay Hải Sản',
  'mi-y-sot-bo-bam': 'Mì Ý Sốt Bò Băm',
  'mi-tron-ten-lua': 'Mì Trộn Tên Lửa',
  'mi-ramen-nhat-ban': 'Mì Ramen Nhật Bản',
  'mi-go-xa-xiu': 'Mì Gõ Xá Xíu',
  'mi-bo-kho': 'Mì Bò Kho',
  'chao-long-mien-tay': 'Cháo Lòng Miền Tây',
  'chao-bo-cau-ham': 'Cháo Bồ Câu Hầm',
  'chao-ca-loc-rau-dang': 'Cháo Cá Lóc Rau Đắng',
  'chao-suon-ngu-coc': 'Cháo Sườn Ngũ Cốc',
  'chao-hao-sua': 'Cháo Hào Sữa',
  'chao-thit-bam-trung-bac-thao': 'Cháo Thịt Băm Trứng Bắc Thảo',
  'chao-ech-singapore': 'Cháo Ếch Singapore',
  'chao-luon-nghe': 'Cháo Lươn Nghệ',
  'chao-hai-san-thap-cam': 'Cháo Hải Sản Thập Cẩm',
  'bo-to-tay-ninh-nuong-tang': 'Bò Tơ Tây Ninh Nướng Tảng',
  'suon-cuu-nuong-thao-moc': 'Sườn Cừu Nướng Thảo Mộc',
  'bach-tuoc-nuong-sa-te': 'Bạch Tuộc Nướng Sa Tế',
  'ga-tre-nuong-com-lam': 'Gà Tre Nướng Cơm Lam',
  'vu-heo-nuong-chao': 'Vú Heo Nướng Chao',
  'hau-sua-nuong-mo-hanh': 'Hàu Sữa Nướng Mỡ Hành',
  'ba-chi-bo-my-cuon-nam-kim-cham': 'Ba Chỉ Bò Mỹ Cuộn Nấm',
  'ca-loc-nuong-trui': 'Cá Lóc Nướng Trui',
  'tom-cang-xanh-nuong-muoi-ot': 'Tôm Càng Xanh Nướng Muối Ớt',
  'chan-ga-nuong-quai-thu': 'Chân Gà Nướng Quái Thú',
  'pizza-hai-san-nhiet-doi': 'Pizza Hải Sản Nhiệt Đới',
  'burger-bo-wagyu-pho-mai': 'Burger Bò Wagyu',
  'banh-mi-chao-dac-biet': 'Bánh Mì Chảo',
  'banh-xeo-tom-nhay': 'Bánh Xèo Tôm Nhảy',
  'banh-goi-nhan-thit': 'Bánh Gối Nhân Thịt',
  'banh-sandwich-ga-nuong-bbq': 'Sandwich Gà Nướng',
  'banh-bao-xa-xiu': 'Bánh Bao Xá Xíu',
  'banh-crepe-man': 'Bánh Crepe Mặn',
  'banh-khot-hai-san': 'Bánh Khọt Hải Sản',
  'banh-tacos-bo-cay': 'Bánh Tacos Bò Cay',
  'sup-bao-ngu-vi-ca': 'Súp Bào Ngư Vi Cá',
  'sup-cua-trung-bac-thao': 'Súp Cua Trứng Bắc Thảo',
  'sup-hai-san-toc-tien': 'Súp Hải Sản Tóc Tiên',
  'sup-bap-ga-xe': 'Súp Bắp Gà Xé',
  'sup-bi-do-kem-tuoi': 'Súp Bí Đỏ Kem Tươi',
  'sup-hai-sam-dong-co': 'Súp Hải Sâm Đông Cô',
  'sup-luon-xu-nghe': 'Súp Lươn Xứ Nghệ',
  'sup-hoanh-thanh-tom-thit': 'Súp Hoành Thánh',
  'sup-kem-nam-bao-ngu': 'Súp Kem Nấm',
  'sup-rong-bien-thit-bam': 'Súp Rong Biển',
  'soda-blue-ocean': 'Soda Blue Ocean',
  'soda-dau-tay-basil': 'Soda Dâu Tây Basil',
  'soda-chanh-day-tui-loc': 'Soda Chanh Dây',
  'soda-dao-mieng': 'Soda Đào Miếng',
  'soda-viet-quat-kem-tuoi': 'Soda Việt Quất Kem',
  'soda-tao-xanh-bac-ha': 'Soda Táo Xanh Bạc Hà',
  'soda-kiwi-tuoi': 'Soda KiWi Tươi',
  'soda-chanh-muoi-co-dien': 'Soda Chanh Muối',
  'soda-cherry-do': 'Soda Cherry Đỏ',
  'soda-mixed-berries': 'Soda Mixed Berries',
  'nuoc-ep-cam-vang': 'Nước Ép Cam Vàng',
  'nuoc-ep-tao-do': 'Nước Ép Táo Đỏ',
  'nuoc-ep-dua': 'Nước Ép Dứa',
  'nuoc-ep-dua-hau': 'Nước Ép Dưa Hấu',
  'nuoc-ep-ca-rot-sua': 'Nước Ép Cà Rốt Sữa',
  'nuoc-ep-oi-hong': 'Nước Ép Ổi Hồng',
  'nuoc-ep-can-tay-mix-tao': 'Nước Ép Cần Tây Táo',
  'nuoc-ep-buoi-hong': 'Nước Ép Bưởi Hồng',
  'nuoc-ep-luu-do': 'Nước Ép Lựu Đỏ',
  'nuoc-ep-chanh-day': 'Nước Ép Chanh Dây',
  'tra-sua-tran-chau-duong-den': 'Trà Sữa Trân Châu Đường Đen',
  'tra-sua-matcha-nhat-ban': 'Trà Sữa Matcha',
  'tra-sua-khoai-mon-tuoi': 'Trà Sữa Khoai Môn',
  'hong-tra-sua-milkfoam': 'Hồng Trà Sữa Milkfoam',
  'tra-sua-thai-xanh': 'Trà Sữa Thái Xanh',
  'tra-sua-o-long-nuong': 'Trà Sữa Ô Long Nướng',
  'tra-sua-kem-trung-chay': 'Trà Sữa Kem Trứng Cháy',
  'tra-sua-socola-bac-ha': 'Trà Sữa Socola Bạc Hà',
  'tra-sua-hat-de-cuoi': 'Trà Sữa Hạt Dẻ Cười',
  'luc-tra-sua-suong-sao': 'Lục Trà Sữa Sương Sáo',
  'sinh-to-bo-sap': 'Sinh Tố Bơ Sáp',
  'sinh-to-xoai-cat': 'Sinh Tố Xoài Cát',
  'sinh-to-mang-cau': 'Sinh Tố Mãng Cầu',
  'sinh-to-sapoche': 'Sinh Tố Sapoche',
  'sinh-to-dau-tay-da-lat': 'Sinh Tố Dâu Tây',
  'sinh-to-viet-quat-sua-chua': 'Sinh Tố Việt Quất',
  'sinh-to-dua-sap': 'Sinh Tố Dừa Sáp',
  'sinh-to-chuoi-bo-dau-phong': 'Sinh Tố Chuối Bơ Đậu Phộng',
  'sinh-to-thanh-long-do': 'Sinh Tố Thanh Long Đỏ',
  'sinh-to-mit-thai': 'Sinh Tố Mít Thái',
  'ca-phe-sua-da-sai-gon': 'Cà Phê Sữa Đá',
  'ca-phe-trung-ha-noi': 'Cà Phê Trứng',
  'bac-xiu-da': 'Bạc Xỉu Đá',
  'ca-phe-muoi-xu-hue': 'Cà Phê Muối',
  'ca-phe-cot-dua-da-xay': 'Cà Phê Cốt Dừa',
  'cappuccino-y': 'Cappuccino',
  'caramel-macchiato': 'Caramel Macchiato',
  'latte-nghe-thuat': 'Latte',
  'cold-brew-cam-sa': 'Cold Brew Cam Sả',
  'americano-da': 'Americano'
};

export default tags;
