const tags: Record<string, string> = {
  'gioi-thieu': 'Giới thiệu',
  'gio-hang': 'Giỏ hàng',
  'thong-tin': 'Thông tin cá nhân',
  'thuc-don': 'Thực đơn',
  'goi-mon': 'Gọi món',
  'khuyen-mai': 'Khuyến mãi',
  'lien-he': 'Liên hệ',
  'goi-mon-nhanh': 'Mua nhanh',
  'thanh-toan': 'Thanh toán',
  'tin-tuc': 'Tin tức',
  'chinh-sach': 'Chính sách',
  'dang-nhap': 'Đăng nhập',
  'dang-ky': 'Đăng ký',
  Password: 'Mật khẩu',
  'change-password': 'Đổi mật khâu',
  'forgot-password': 'Quên mật khẩu',
  'reset-password': 'Đặt lại mật khẩu',
  'san-pham': 'Sản phẩm',
  'yeu-thich': 'Yêu thích',
  'danh-gia': 'Đánh giá',
  'tim-kiem': 'Tìm kiếm',
  'vnpay-payment-result': 'Thông tin thanh toán',
  'thit-tuoi': 'Thịt tươi',
  'san-pham-moi': 'Sản phẩm mới',
  'san-pham-hot': 'Sản phẩm nổi bật',
  'san-pham-giam-gia': 'Sản phẩm giảm giá',
  'san-pham-ban-chay': 'Sản phẩm bán chạy',
  'thuc-uong': 'Thức uống',
  'don-hang-cua-toi': 'Đơn hàng của tôi',
  'price-asc': 'Giá từ thấp đến cao',
  'price-desc': 'Giá từ cao đến thấp',
  'name-asc': 'Tên A-Z',
  'name-desc': 'Tên Z-A',
  'updatedAt-desc': 'Mới nhất',
  'rating-desc': 'Đánh giá cao',
  'soldQuantity-desc': 'Bán chạy',
  'best-seller': 'Bán chạy',
  'com-tam-suon-bi-cha': 'Cơm tấm sườn bì chả',
  'mon-chinh': 'Món chính',
  'mon-chay': 'Món chay',
  'cac-loai-com': 'Các loại cơm',
  'thanh-toan-vnpay': 'Thanh toán VnPay',
  'do-uong': 'Đồ uống',
  'an-vat-trang-mieng': 'Ăn vặt & tráng miệng',
  'mon-co-sup': 'Món có súp',
  'ca-phe': 'Cà phê',
  'nuoc-giai-khat': 'Nước giải khát',
  'tra-sua': 'Trà Sữa',
  'banh-trang': 'Bánh tráng',
  'banh-man': 'Bánh Mặn',
  'banh-ngot': 'Bánh Ngọt',
  'thit-bo': 'Thịt Bò',
  'thit-ga': 'Thịt gà',
  'thit-heo': 'Thịt Heo',
  'tom-su': 'Tôm sú',
  muc: 'Mực',
  'ca-cac-loai': 'Cá các loại',
  'cac-loai-oc': 'Các loại ốc',
  'cu-cai-trang': 'Củ cải trắng',
  'ca-rot': 'Cà rốt',
  'cai-thia': 'Cải thìa',
  'bong-cai': 'Bông cải',
  'nam-meo': 'Nấm mèo',
  'nam-kim-cham': 'Nấm kim châm',
  'nam-moc-nhi': 'Nấm mộc nhỉ',
  'nam-dui-ga': 'Nấm đùi gà',
  'dau-hu-tuoi': 'Đậu hủ tươi',
  'dau-hu-chien': 'Đậu hủ chiên',
  'dau-hu-ki': 'Đậu hũ ki',
  'cha-chay': 'Chả chay',
  'dua-leo': 'Dưa leo',
  'ca-chua': 'Cà chua',
  'gia-do': 'Giá đỗ',
  'rau-xa-lach': 'Rau xà lách',
  'rau-ma': 'Rau má',
  'hoa-chuoi-bap-chuoi': 'Hoa chuối (bắp chuối)',
  'rau-thom-hung-que-hung-lang': 'Rau thơm húng quế - húng láng',
  'rau-muong': 'Rau muống',
  'hanh-tay': 'Hành tây',
  'ngo-gai': 'Ngò gai',
  'hanh-la': 'Hành lá',
  'danh-muc-123': 'Danh mục 123',
  soda: 'Soda ',
  'thit-vit': 'Thịt Vịt',
  'suon-non': 'Sườn Non',
  'cua-bien': 'Cua Biển',
  ca: 'Cá',
  'muc-ong': 'Mực Ống',
  so: 'Sò',
  mi: 'Mì',
  chao: 'Cháo ',
  'nuoc-ep': 'Nước Ép',
  'sinh-to': 'Sinh Tố ',
  'com-chay': 'Cơm Chay',
  'bun-chay': 'Bún Chay',
  'lau-chay': 'Lẩu Chay',
  'mon-xao-chay': 'Món Xào Chay',
  'canh-chay': 'Canh Chay',
  che: 'Chè ',
  kem: 'Kem',
  'sua-chua': 'Sữa Chua',
  'trai-cay': 'Trái Cây',
  'bun-bo-hue': 'Bún bò Huế',
  'ca-phe-sua-da': 'Cà phê sữa đá',
  'bun-cha-ha-noi': 'Bún chả Hà Nội',
  'canh-chua-chay': 'Canh chua chay',
  'tra-sua-tran-chau': 'Trà sữa trân châu',
  'nuoc-ep-cam-tuoi': 'Nước ép cam tươi',
  'banh-trang-cha-bong': 'Bánh tráng chà bông',
  'banh-da-lon': 'Bánh da lợn',
  'banh-khoai-mo-chien': 'Bánh khoai mỡ chiên',
  'banh-trang-tac': 'Bánh tráng tắc',
  'chao-ga-xe-phay': 'Cháo gà xé phay',
  'nem-nuong': 'Nem nướng',
  'snack-bim-bim': 'Snack (Bim bim)',
  'keo-ngot': 'Kẹo ngọt',
  'rau-cau': 'Rau câu',
  'nguyen-thuy-linh': 'Nguyễn Thùy Linh',
  'nguyen-thi-meo-meo': 'Nguyễn Thị Mèo Meo',
  'com-com': 'Cơm cớm',
  'banh-cuon': 'Bánh cuốn',
  'sua-chua-trai-cay': 'Sữa chua trái cây',
  'xoi-xoai': 'Xôi xoài',
  'xoi-ngot-la-dua': 'Xôi ngọt lá dứa',
  'cha-gio-chien': 'Chả giò chiên',
  'bun-bo-chay': 'Bún bò chay',
  'com-rang-dua-chuot': 'Cơm rang dưa chuột',
  'bun-mam-chay': 'Bún Mắm Chay',
  'thit-ngong': 'Thịt ngỗng',
  'bo-dau-phong': 'Bơ đậu phộng',
  'mon-nuong': 'Món nướng',
  'ga-nuong-mat-ong': 'Gà nướng mật ong',
  'ca-nuong-trui-mien-tay': 'Cá nướng trui miền Tây',
  'bo-nuong-la-lot': 'Bò nướng lá lốt',
  'suon-nuong-sa-ot': 'Sườn nướng sả ớt',
  'sup-ga-ngo-non-bac-bo': 'Súp gà ngô non Bắc Bộ',
  'sup-ca-hoi-rau-cu': 'Súp cá hồi rau củ',
  'sup-bap-bo-hue': 'Súp bắp bò Huế',
  'sup-nam-hai-san': 'Súp nấm hải sản',
  'xien-que-do-chien': 'Xiên Que & Đồ Chiên',
  'com-sen-bach-diep': 'Cơm Sen Bách Diệp',
  'com-tam-chay': 'Cơm Tấm Chay',
  'com-chien-duong-chau-chay': 'Cơm Chiên Dương Châu Chay',
  'com-dui-ga-chay': 'Cơm Đùi Gà Chay',
  'com-tron-han-quoc-chay': 'Cơm Trộn Hàn Quốc Chay',
  'com-nieu-rau-cu': 'Cơm Niêu Rau Củ',
  'com-chay-kho-quet-chay': 'Cơm Cháy Kho Quẹt Chay',
  'com-lam-thit-nuong-chay': 'Cơm Lam Thịt Nướng Chay',
  'com-ga-hai-nam-chay': 'Cơm Gà Hải Nam Chay',
  'com-cuon-rong-bien-chay': 'Cơm Cuộn Rong Biển Chay',
  'bun-bo-hue-chay': 'Bún Bò Huế Chay',
  'bun-rieu-chay': 'Bún Riêu Chay',
  'bun-cha-gio-chay': 'Bún Chả Giò Chay',
  'bun-thang-chay': 'Bún Thang Chay',
  'bun-moc-chay': 'Bún Mọc Chay',
  'bun-thit-nuong-chay': 'Bún Thịt Nướng Chay',
  'bun-thai-chay': 'Bún Thái Chay',
  'bun-ca-chay': 'Bún Cá Chay',
  'bun-xao-nghe-chay': 'Bún Xào Nghệ Chay',
  'lau-nam-thien-nhien': 'Lẩu Nấm Thiên Nhiên',
  'lau-thai-chua-cay-chay': 'Lẩu Thái Chua Cay Chay',
  'lau-chao-do-chay': 'Lẩu Chao Đỏ Chay',
  'lau-tieu-xanh-chay': 'Lẩu Tiêu Xanh Chay',
  'lau-rieu-cua-dong-chay': 'Lẩu Riêu Cua Đồng Chay',
  'lau-kho-qua-rung-chay': 'Lẩu Khổ Qua Rừng Chay',
  'lau-mam-chay-nam-bo': 'Lẩu Mắm Chay Nam Bộ',
  'lau-kim-chi-chay': 'Lẩu Kim Chi Chay',
  'lau-an-nhien': 'Lẩu An Nhiên',
  'lau-tha-phan-thiet-chay': 'Lẩu Thả Phan Thiết Chay',
  'rau-cu-thap-cam-xao': 'Rau Củ Thập Cẩm Xào',
  'nam-bao-ngu-xao-sa-ot': 'Nấm Bào Ngư Xào Sả Ớt',
  'dau-hu-xao-rau-cu': 'Đậu Hũ Xào Rau Củ',
  'kho-qua-xao-dau-hu': 'Khổ Qua Xào Đậu Hũ',
  'mi-can-xao-chua-ngot': 'Mì Căn Xào Chua Ngọt',
  'bong-cai-xao-nam-huong': 'Bông Cải Xào Nấm Hương',
  'dau-que-xao-jambon-chay': 'Đậu Que Xào Jambon Chay',
  'hu-tieu-xao-chay': 'Hủ Tiếu Xào Chay',
  'gia-do-xao-dau-hu-ki': 'Giá Đỗ Xào Đậu Hũ Ki',
  'mang-tay-xao-toi-chay': 'Măng Tây Xào Tỏi Chay',
  'canh-chua-nam-bo-chay': 'Canh Chua Nam Bộ Chay',
  'canh-kho-qua-rung': 'Canh Khổ Qua Rừng',
  'canh-rau-cu-thap-cam': 'Canh Rau Củ Thập Cẩm',
  'canh-rong-bien-dau-hu': 'Canh Rong Biển Đậu Hũ',
  'canh-nam-hat-sen': 'Canh Nấm Hạt Sen',
  'canh-chua-cay-kieu-thai': 'Canh Chua Cay Kiểu Thái',
  'canh-kiem-mien-tay': 'Canh Kiểm Miền Tây',
  'canh-bau-nau-tom-chay': 'Canh Bầu Nấu Tôm Chay',
  'canh-kim-chi-dau-hu-non': 'Canh Kim Chi Đậu Hũ Non',
  'canh-kho-qua-mo-tim': 'Canh Khoai Mỡ Tím',
  'che-thai-sau-rieng': 'Chè Thái Sầu Riêng',
  'che-buoi-an-giang': 'Chè Bưởi An Giang',
  'che-duong-nhan': 'Chè Dưỡng Nhan',
  'che-khuc-bach': 'Chè Khúc Bạch',
  'che-troi-nuoc-ngu-sac': 'Chè Trôi Nước Ngũ Sắc',
  'che-thach-nhan-sen': 'Chè Thạch Nhãn Sen',
  'che-khoai-deo-dai-loan': 'Chè Khoai Dẻo Đài Loan',
  'che-dau-ngu-cung-dinh': 'Chè Đậu Ngự Cung Đình',
  'che-chuoi-chung': 'Chè Chuối Chưng',
  'che-sam-bo-luong': 'Chè Sâm Bổ Lượng',
  'banh-mousse-chanh-leo': 'Bánh Mousse Chanh Leo',
  'banh-tiramisu': 'Bánh Tiramisu',
  'banh-brownie-socola-hanh-nhan': 'Bánh Brownie Socola Hạnh Nhân',
  'banh-su-kem': 'Bánh Su Kem',
  'banh-bong-lan-cuon-mut-dau': 'Bánh Bông Lan Cuộn Mứt Dâu',
  'banh-tart-trai-cay': 'Bánh Tart Trái Cây',
  'banh-carrot-cake': 'Bánh Cà Rốt Chay',
  'banh-donut-duong-chay': 'Bánh Donut Đường Chay',
  'banh-crepe-sau-rieng': 'Bánh Crepe Sầu Riêng',
  'banh-mi-hoa-cuc': 'Bánh Mì Hoa Cúc',
  'com-ga-xoi-mo': 'Cơm Gà Xối Mỡ',
  'com-suon-nuong-bbq': 'Cơm Sườn Nướng BBQ',
  'com-bo-luc-lac': 'Cơm Bò Lúc Lắc',
  'com-chien-hai-san': 'Cơm Chiên Hải Sản',
  'com-ca-kho-to': 'Cơm Cá Kho Tộ',
  'com-thit-kho-trung': 'Cơm Thịt Kho Trứng',
  'com-dui-vit-quay': 'Cơm Đùi Vịt Quay',
  'com-xa-xiu-quang-dong': 'Cơm Xá Xíu Quảng Đông',
  'com-muc-nhoi-thit-chien': 'Cơm Mực Nhồi Thịt Chiên',
  'mi-quang-ga-ta': 'Mì Quảng Gà Ta',
  'mi-vit-tiem': 'Mì Vịt Tiềm',
  'mi-hoanh-thanh-xa-xiu': 'Mì Hoành Thánh Xá Xíu',
  'mi-xao-gion-hai-san': 'Mì Xào Giòn Hải Sản',
  'mi-cay-hai-san': 'Mì Cay Hải Sản',
  'mi-y-sot-bo-bam': 'Mì Ý Sốt Bò Băm',
  'mi-tron-ten-lua': 'Mì Trộn Tên Lửa',
  'mi-ramen-nhat-ban': 'Mì Ramen Nhật Bản',
  'mi-go-xa-xiu': 'Mì Gõ Xá Xíu',
  'mi-bo-kho': 'Mì Bò Kho',
  'chao-long-mien-tay': 'Cháo Lòng Miền Tây',
  'chao-bo-cau-ham': 'Cháo Bồ Câu Hầm',
  'chao-ca-loc-rau-dang': 'Cháo Cá Lóc Rau Đắng',
  'chao-suon-ngu-coc': 'Cháo Sườn Ngũ Cốc',
  'chao-hao-sua': 'Cháo Hào Sữa',
  'chao-thit-bam-trung-bac-thao': 'Cháo Thịt Băm Trứng Bắc Thảo',
  'chao-ech-singapore': 'Cháo Ếch Singapore',
  'chao-luon-nghe': 'Cháo Lươn Nghệ',
  'chao-hai-san-thap-cam': 'Cháo Hải Sản Thập Cẩm',
  'bo-to-tay-ninh-nuong-tang': 'Bò Tơ Tây Ninh Nướng Tảng',
  'suon-cuu-nuong-thao-moc': 'Sườn Cừu Nướng Thảo Mộc',
  'bach-tuoc-nuong-sa-te': 'Bạch Tuộc Nướng Sa Tế',
  'ga-tre-nuong-com-lam': 'Gà Tre Nướng Cơm Lam',
  'vu-heo-nuong-chao': 'Vú Heo Nướng Chao',
  'hau-sua-nuong-mo-hanh': 'Hàu Sữa Nướng Mỡ Hành',
  'ba-chi-bo-my-cuon-nam-kim-cham': 'Ba Chỉ Bò Mỹ Cuộn Nấm Kim Châm',
  'ca-loc-nuong-trui': 'Cá Lóc Nướng Trui',
  'tom-cang-xanh-nuong-muoi-ot': 'Tôm Càng Xanh Nướng Muối Ớt',
  'chan-ga-nuong-quai-thu': 'Chân Gà Nướng Quái Thú',
  'pizza-hai-san-nhiet-doi': 'Pizza Hải Sản Nhiệt Đới',
  'burger-bo-wagyu-pho-mai': 'Burger Bò Wagyu Phô Mai',
  'banh-mi-chao-dac-biet': 'Bánh Mì Chảo Đặc Biệt',
  'banh-xeo-tom-nhay': 'Bánh Xèo Tôm Nhảy',
  'banh-goi-nhan-thit': 'Bánh Gối Nhân Thịt',
  'banh-sandwich-ga-nuong-bbq': 'Bánh Sandwich Gà Nướng BBQ',
  'banh-bao-xa-xiu': 'Bánh Bao Xá Xíu',
  'banh-crepe-man': 'Bánh Crepe Mặn',
  'banh-khot-hai-san': 'Bánh Khọt Hải Sản',
  'banh-tacos-bo-cay': 'Bánh Tacos Bò Cay',
  'sup-bao-ngu-vi-ca': 'Súp Bào Ngư Vi Cá',
  'sup-cua-trung-bac-thao': 'Súp Cua Trứng Bắc Thảo',
  'sup-hai-san-toc-tien': 'Súp Hải Sản Tóc Tiên',
  'sup-bap-ga-xe': 'Súp Bắp Gà Xé',
  'sup-bi-do-kem-tuoi': 'Súp Bí Đỏ Kem Tươi',
  'sup-hai-sam-dong-co': 'Súp Hải Sâm Đông Cô',
  'sup-luon-xu-nghe': 'Súp Lươn Xứ Nghệ',
  'sup-hoanh-thanh-tom-thit': 'Súp Hoành Thánh Tôm Thịt',
  'sup-kem-nam-bao-ngu': 'Súp Kem Nấm Bào Ngư',
  'sup-rong-bien-thit-bam': 'Súp Rong Biển Thịt Băm',
  'soda-blue-ocean': 'Soda Blue Ocean',
  'soda-dau-tay-basil': 'Soda Dâu Tây Basil',
  'soda-chanh-day-tui-loc': 'Soda Chanh Dây Túi Lọc',
  'soda-dao-mieng': 'Soda Đào Miếng',
  'soda-viet-quat-kem-tuoi': 'Soda Việt Quất Kem Tươi',
  'soda-tao-xanh-bac-ha': 'Soda Táo Xanh Bạc Hà',
  'soda-kiwi-tuoi': 'Soda KiWi Tươi',
  'soda-chanh-muoi-co-dien': 'Soda Chanh Muối Cổ Điển',
  'soda-cherry-do': 'Soda Cherry Đỏ',
  'soda-mixed-berries': 'Soda Mixed Berries',
  'nuoc-ep-cam-vang': 'Nước Ép Cam Vàng',
  'nuoc-ep-tao-do': 'Nước Ép Táo Đỏ',
  'nuoc-ep-dua': 'Nước Ép Dứa',
  'nuoc-ep-dua-hau': 'Nước Ép Dưa Hấu',
  'nuoc-ep-ca-rot-sua': 'Nước Ép Cà Rốt Sữa',
  'nuoc-ep-oi-hong': 'Nước Ép Ổi Hồng',
  'nuoc-ep-can-tay-mix-tao': 'Nước Ép Cần Tây Mix Táo',
  'nuoc-ep-buoi-hong': 'Nước Ép Bưởi Hồng',
  'nuoc-ep-luu-do': 'Nước Ép Lựu Đỏ',
  'nuoc-ep-chanh-day': 'Nước Ép Chanh Dây',
  'tra-sua-tran-chau-duong-den': 'Trà Sữa Trân Châu Đường Đen',
  'tra-sua-matcha-nhat-ban': 'Trà Sữa Matcha Nhật Bản',
  'tra-sua-khoai-mon-tuoi': 'Trà Sữa Khoai Môn Tươi',
  'hong-tra-sua-milkfoam': 'Hồng Trà Sữa Milkfoam',
  'tra-sua-thai-xanh': 'Trà Sữa Thái Xanh',
  'tra-sua-o-long-nuong': 'Trà Sữa Ô Long Nướng',
  'tra-sua-kem-trung-chay': 'Trà Sữa Kem Trứng Cháy',
  'tra-sua-socola-bac-ha': 'Trà Sữa Socola Bạc Hà',
  'tra-sua-hat-de-cuoi': 'Trà Sữa Hạt Dẻ Cười',
  'luc-tra-sua-suong-sao': 'Lục Trà Sữa Sương Sáo',
  'sinh-to-bo-sap': 'Sinh Tố Bơ Sáp',
  'sinh-to-xoai-cat': 'Sinh Tố Xoài Cát',
  'sinh-to-mang-cau': 'Sinh Tố Mãng Cầu',
  'sinh-to-sapoche': 'Sinh Tố Sapoche',
  'sinh-to-dau-tay-da-lat': 'Sinh Tố Dâu Tây Đà Lạt',
  'sinh-to-viet-quat-sua-chua': 'Sinh Tố Việt Quất Sữa Chua',
  'sinh-to-dua-sap': 'Sinh Tố Dừa Sáp',
  'sinh-to-chuoi-bo-dau-phong': 'Sinh Tố Chuối Bơ Đậu Phộng',
  'sinh-to-thanh-long-do': 'Sinh Tố Thanh Long Đỏ',
  'sinh-to-mit-thai': 'Sinh Tố Mít Thái',
  'ca-phe-sua-da-sai-gon': 'Cà Phê Sữa Đá Sài Gòn',
  'ca-phe-trung-ha-noi': 'Cà Phê Trứng Hà Nội',
  'bac-xiu-da': 'Bạc Xỉu Đá',
  'ca-phe-muoi-xu-hue': 'Cà Phê Muối Xứ Huế',
  'ca-phe-cot-dua-da-xay': 'Cà Phê Cốt Dừa Đá Xay',
  'cappuccino-y': 'Cappuccino Ý',
  'caramel-macchiato': 'Caramel Macchiato',
  'latte-nghe-thuat': 'Latte Nghệ Thuật',
  'cold-brew-cam-sa': 'Cold Brew Cam Sả',
  'americano-da': 'Americano Đá',
  'banh-bao-nhan-thit-xa-xiu': 'Bánh Bao Nhân Thịt Xá Xíu',
  'banh-carrot-cake-banh-ca-rot': 'Bánh Carrot Cake (Bánh Cà Rốt)',
  'mi-y-sot-bo-bam-spaghetti': 'Mì Ý Sốt Bò Băm (Spaghetti)',
  'banh-goi-nhan-thit-trung-cut': 'Bánh Gối Nhân Thịt Trứng Cút',
  'sinh-to-sapoche-hong-xiem': 'Sinh Tố Sapoche (Hồng Xiêm)',
  'nuoc-ep-dua-thom': 'Nước Ép Dứa (Thơm)',
  'banh-crepe-nhan-thit-xong-khoi': 'Bánh Crepe Nhân Thịt Xông Khói',
  'lau-an-nhien-lau-sen': 'Lẩu An Nhiên (Lẩu Sen)',
  'mi-cay-hai-san-7-cap-do': 'Mì Cay Hải Sản 7 Cấp Độ',
  'ba-chi-heo': 'Ba chỉ heo',
  'suờn-heo': 'Sườn heo',
  'nac-heo': 'Nạc heo',
  'bắp-bo': 'Bắp bò',
  'nam-bo': 'Nạm bò',
  'gầu-bo': 'Gầu bò',
  'ức-ga': 'Ức gà',
  'dui-ga': 'Đùi gà',
  'canh-ga': 'Cánh gà',
  'thit-cừu': 'Thịt cừu',
  cua: 'Cua',
  'ca-hồi': 'Cá hồi',
  'ca-basa': 'Cá basa',
  'ca-ro': 'Cá rô',
  'muc-nang': 'Mực nang',
  'mực-ống': 'Mực ống',
  'bach-tuộc': 'Bạch tuộc',
  ngheu: 'Nghêu',
  hến: 'Hến',
  'ca-rốt': 'Cà rốt',
  'cu-cai-trắng': 'Củ cải trắng',
  'cu-dền': 'Củ dền',
  'su-su': 'Su su',
  'bắp-cai': 'Bắp cải',
  'cai-xanh': 'Cải xanh',
  'rau-muống': 'Rau muống',
  'rau-mồng-toi': 'Rau mồng tơi',
  'khổ-qua': 'Khổ qua',
  'dậu-que': 'Đậu que',
  'bắp-ngo': 'Bắp ngô',
  mang: 'Măng',
  'nấm-rom': 'Nấm rơm',
  'nấm-bao-ngu': 'Nấm bào ngư',
  'nấm-kim-cham': 'Nấm kim châm',
  'nấm-dong-co': 'Nấm đông cô',
  'nấm-huong': 'Nấm hương',
  'dậu-hu': 'Đậu hũ',
  'dậu-hu-non': 'Đậu hũ non',
  'tau-hu-ky': 'Tàu hũ ky',
  'dậu-xanh': 'Đậu xanh',
  'dậu-do': 'Đậu đỏ',
  'dậu-den': 'Đậu đen',
  'dậu-phộng': 'Đậu phộng',
  bun: 'Bún',
  phở: 'Phở',
  miến: 'Miến',
  'hu-tiếu': 'Hủ tiếu',
  'banh-canh': 'Bánh canh',
  'bun-tuoi': 'Bún tươi',
  gao: 'Gạo',
  'com-trang': 'Cơm trắng',
  muối: 'Muối',
  duờng: 'Đường',
  tieu: 'Tiêu',
  'nuớc-mắm': 'Nước mắm',
  'nuớc-tuong': 'Nước tương',
  'dầu-an': 'Dầu ăn',
  'dầu-hao': 'Dầu hào',
  'tuong-ớt': 'Tương ớt',
  'tuong-ca': 'Tương cà',
  'mắm-ruốc': 'Mắm ruốc',
  'mắm-tom': 'Mắm tôm',
  gừng: 'Gừng',
  ớt: 'Ớt',
  'hung-quế': 'Húng quế',
  'trứng-ga': 'Trứng gà',
  'trứng-vit': 'Trứng vịt',
  'trứng-cut': 'Trứng cút',
  'cha-ca': 'Chả cá',
  'cha-lua': 'Chả lụa',
  'xuc-xich': 'Xúc xích',
  'thit-vien': 'Thịt viên',
  'gio-sống': 'Giò sống',
  'nem-chua': 'Nem chua',
  'lap-xuởng': 'Lạp xưởng',
  'thit-heo-tuoi': 'Thịt heo tươi',
  'thit-heo-dong-lanh': 'Thịt heo đông lạnh',
  'thit-heo-hữu-co': 'Thịt heo hữu cơ',
  'ba-chi-heo-tuoi': 'Ba chỉ heo tươi',
  'ba-chi-heo-dong-lanh': 'Ba chỉ heo đông lạnh',
  'ba-chi-heo-hữu-co': 'Ba chỉ heo hữu cơ',
  'suờn-heo-tuoi': 'Sườn heo tươi',
  'suờn-heo-dong-lanh': 'Sườn heo đông lạnh',
  'suờn-heo-hữu-co': 'Sườn heo hữu cơ',
  'nac-heo-tuoi': 'Nạc heo tươi',
  'nac-heo-dong-lanh': 'Nạc heo đông lạnh',
  'nac-heo-hữu-co': 'Nạc heo hữu cơ',
  'thit-bo-tuoi': 'Thịt bò tươi',
  'thit-bo-dong-lanh': 'Thịt bò đông lạnh',
  'thit-bo-hữu-co': 'Thịt bò hữu cơ',
  'bắp-bo-tuoi': 'Bắp bò tươi',
  'bắp-bo-dong-lanh': 'Bắp bò đông lạnh',
  'bắp-bo-hữu-co': 'Bắp bò hữu cơ',
  'nam-bo-tuoi': 'Nạm bò tươi',
  'nam-bo-dong-lanh': 'Nạm bò đông lạnh',
  'nam-bo-hữu-co': 'Nạm bò hữu cơ',
  'gầu-bo-tuoi': 'Gầu bò tươi',
  'gầu-bo-dong-lanh': 'Gầu bò đông lạnh',
  'gầu-bo-hữu-co': 'Gầu bò hữu cơ',
  'thit-ga-tuoi': 'Thịt gà tươi',
  'thit-ga-dong-lanh': 'Thịt gà đông lạnh',
  'thit-ga-hữu-co': 'Thịt gà hữu cơ',
  'ức-ga-tuoi': 'Ức gà tươi',
  'ức-ga-dong-lanh': 'Ức gà đông lạnh',
  'ức-ga-hữu-co': 'Ức gà hữu cơ',
  'dui-ga-tuoi': 'Đùi gà tươi',
  'dui-ga-dong-lanh': 'Đùi gà đông lạnh',
  'dui-ga-hữu-co': 'Đùi gà hữu cơ',
  'canh-ga-tuoi': 'Cánh gà tươi',
  'canh-ga-dong-lanh': 'Cánh gà đông lạnh',
  'canh-ga-hữu-co': 'Cánh gà hữu cơ',
  'thit-vit-tuoi': 'Thịt vịt tươi',
  'thit-vit-dong-lanh': 'Thịt vịt đông lạnh',
  'thit-vit-hữu-co': 'Thịt vịt hữu cơ',
  'thit-de-tuoi': 'Thịt dê tươi',
  'thit-de-dong-lanh': 'Thịt dê đông lạnh',
  'thit-de-hữu-co': 'Thịt dê hữu cơ',
  'thit-cừu-tuoi': 'Thịt cừu tươi',
  'thit-cừu-dong-lanh': 'Thịt cừu đông lạnh',
  'thit-cừu-hữu-co': 'Thịt cừu hữu cơ',
  'thit-nai': 'Thịt nai',
  'thit-nai-tuoi': 'Thịt nai tươi',
  'thit-nai-dong-lanh': 'Thịt nai đông lạnh',
  'thit-nai-hữu-co': 'Thịt nai hữu cơ',
  'thit-tho': 'Thịt thỏ',
  'thit-tho-tuoi': 'Thịt thỏ tươi',
  'thit-tho-dong-lanh': 'Thịt thỏ đông lạnh',
  'thit-tho-hữu-co': 'Thịt thỏ hữu cơ',
  'thit-chim-cut': 'Thịt chim cút',
  'thit-chim-cut-tuoi': 'Thịt chim cút tươi',
  'thit-chim-cut-dong-lanh': 'Thịt chim cút đông lạnh',
  'thit-chim-cut-hữu-co': 'Thịt chim cút hữu cơ',
  'thit-bồ-cau': 'Thịt bồ câu',
  'thit-bồ-cau-tuoi': 'Thịt bồ câu tươi',
  'thit-bồ-cau-dong-lanh': 'Thịt bồ câu đông lạnh',
  'thit-bồ-cau-hữu-co': 'Thịt bồ câu hữu cơ',
  'gan-heo': 'Gan heo',
  'gan-heo-tuoi': 'Gan heo tươi',
  'gan-heo-dong-lanh': 'Gan heo đông lạnh',
  'gan-heo-hữu-co': 'Gan heo hữu cơ',
  'tim-heo': 'Tim heo',
  'tim-heo-tuoi': 'Tim heo tươi',
  'tim-heo-dong-lanh': 'Tim heo đông lạnh',
  'tim-heo-hữu-co': 'Tim heo hữu cơ',
  'bao-tử-heo': 'Bao tử heo',
  'bao-tử-heo-tuoi': 'Bao tử heo tươi',
  'bao-tử-heo-dong-lanh': 'Bao tử heo đông lạnh',
  'bao-tử-heo-hữu-co': 'Bao tử heo hữu cơ',
  'tai-heo': 'Tai heo',
  'tai-heo-tuoi': 'Tai heo tươi',
  'tai-heo-dong-lanh': 'Tai heo đông lạnh',
  'tai-heo-hữu-co': 'Tai heo hữu cơ',
  'chan-heo': 'Chân heo',
  'chan-heo-tuoi': 'Chân heo tươi',
  'chan-heo-dong-lanh': 'Chân heo đông lạnh',
  'chan-heo-hữu-co': 'Chân heo hữu cơ',
  'tom-tuoi': 'Tôm tươi',
  'tom-dong-lanh': 'Tôm đông lạnh',
  'tom-hữu-co': 'Tôm hữu cơ',
  'tom-su-tuoi': 'Tôm sú tươi',
  'tom-su-dong-lanh': 'Tôm sú đông lạnh',
  'tom-su-hữu-co': 'Tôm sú hữu cơ',
  'tom-the-tuoi': 'Tôm thẻ tươi',
  'tom-the-dong-lanh': 'Tôm thẻ đông lạnh',
  'tom-the-hữu-co': 'Tôm thẻ hữu cơ',
  'cua-tuoi': 'Cua tươi',
  'cua-dong-lanh': 'Cua đông lạnh',
  'cua-hữu-co': 'Cua hữu cơ',
  'ghe-tuoi': 'Ghẹ tươi',
  'ghe-dong-lanh': 'Ghẹ đông lạnh',
  'ghe-hữu-co': 'Ghẹ hữu cơ',
  'ca-hồi-tuoi': 'Cá hồi tươi',
  'ca-hồi-dong-lanh': 'Cá hồi đông lạnh',
  'ca-hồi-hữu-co': 'Cá hồi hữu cơ',
  'ca-thu-tuoi': 'Cá thu tươi',
  'ca-thu-dong-lanh': 'Cá thu đông lạnh',
  'ca-thu-hữu-co': 'Cá thu hữu cơ',
  'ca-basa-tuoi': 'Cá basa tươi',
  'ca-basa-dong-lanh': 'Cá basa đông lạnh',
  'ca-basa-hữu-co': 'Cá basa hữu cơ',
  'ca-loc-tuoi': 'Cá lóc tươi',
  'ca-loc-dong-lanh': 'Cá lóc đông lạnh',
  'ca-loc-hữu-co': 'Cá lóc hữu cơ',
  'ca-ro-tuoi': 'Cá rô tươi',
  'ca-ro-dong-lanh': 'Cá rô đông lạnh',
  'ca-ro-hữu-co': 'Cá rô hữu cơ',
  'ca-ngừ': 'Cá ngừ',
  'ca-ngừ-tuoi': 'Cá ngừ tươi',
  'ca-ngừ-dong-lanh': 'Cá ngừ đông lạnh',
  'ca-ngừ-hữu-co': 'Cá ngừ hữu cơ',
  'ca-tre': 'Cá trê',
  'ca-tre-tuoi': 'Cá trê tươi',
  'ca-tre-dong-lanh': 'Cá trê đông lạnh',
  'ca-tre-hữu-co': 'Cá trê hữu cơ',
  'ca-chep': 'Cá chép',
  'ca-chep-tuoi': 'Cá chép tươi',
  'ca-chep-dong-lanh': 'Cá chép đông lạnh',
  'ca-chep-hữu-co': 'Cá chép hữu cơ',
  'mực-tuoi': 'Mực tươi',
  'mực-dong-lanh': 'Mực đông lạnh',
  'mực-hữu-co': 'Mực hữu cơ',
  'mực-ống-tuoi': 'Mực ống tươi',
  'mực-ống-dong-lanh': 'Mực ống đông lạnh',
  'mực-ống-hữu-co': 'Mực ống hữu cơ',
  'bach-tuộc-tuoi': 'Bạch tuộc tươi',
  'bach-tuộc-dong-lanh': 'Bạch tuộc đông lạnh',
  'bach-tuộc-hữu-co': 'Bạch tuộc hữu cơ',
  'ngheu-tuoi': 'Nghêu tươi',
  'ngheu-dong-lanh': 'Nghêu đông lạnh',
  'ngheu-hữu-co': 'Nghêu hữu cơ',
  'so-tuoi': 'Sò tươi',
  'so-dong-lanh': 'Sò đông lạnh',
  'so-hữu-co': 'Sò hữu cơ',
  'hến-tuoi': 'Hến tươi',
  'hến-dong-lanh': 'Hến đông lạnh',
  'hến-hữu-co': 'Hến hữu cơ',
  hau: 'Hàu',
  'hau-tuoi': 'Hàu tươi',
  'hau-dong-lanh': 'Hàu đông lạnh',
  'hau-hữu-co': 'Hàu hữu cơ',
  'ca-rốt-tuoi': 'Cà rốt tươi',
  'ca-rốt-dong-lanh': 'Cà rốt đông lạnh',
  'ca-rốt-hữu-co': 'Cà rốt hữu cơ',
  'khoai-tay-tuoi': 'Khoai tây tươi',
  'khoai-tay-dong-lanh': 'Khoai tây đông lạnh',
  'khoai-tay-hữu-co': 'Khoai tây hữu cơ',
  'khoai-lang-tuoi': 'Khoai lang tươi',
  'khoai-lang-dong-lanh': 'Khoai lang đông lạnh',
  'khoai-lang-hữu-co': 'Khoai lang hữu cơ',
  'cu-cai-trắng-tuoi': 'Củ cải trắng tươi',
  'cu-cai-trắng-dong-lanh': 'Củ cải trắng đông lạnh',
  'cu-cai-trắng-hữu-co': 'Củ cải trắng hữu cơ',
  'cu-dền-tuoi': 'Củ dền tươi',
  'cu-dền-dong-lanh': 'Củ dền đông lạnh',
  'cu-dền-hữu-co': 'Củ dền hữu cơ',
  'bi-do-tuoi': 'Bí đỏ tươi',
  'bi-do-dong-lanh': 'Bí đỏ đông lạnh',
  'bi-do-hữu-co': 'Bí đỏ hữu cơ',
  'bi-xanh-tuoi': 'Bí xanh tươi',
  'bi-xanh-dong-lanh': 'Bí xanh đông lạnh',
  'bi-xanh-hữu-co': 'Bí xanh hữu cơ',
  'su-su-tuoi': 'Su su tươi',
  'su-su-dong-lanh': 'Su su đông lạnh',
  'su-su-hữu-co': 'Su su hữu cơ',
  'bắp-cai-tuoi': 'Bắp cải tươi',
  'bắp-cai-dong-lanh': 'Bắp cải đông lạnh',
  'bắp-cai-hữu-co': 'Bắp cải hữu cơ',
  'cai-thia-tuoi': 'Cải thìa tươi',
  'cai-thia-dong-lanh': 'Cải thìa đông lạnh',
  'cai-thia-hữu-co': 'Cải thìa hữu cơ',
  'cai-xanh-tuoi': 'Cải xanh tươi',
  'cai-xanh-dong-lanh': 'Cải xanh đông lạnh',
  'cai-xanh-hữu-co': 'Cải xanh hữu cơ',
  'rau-muống-tuoi': 'Rau muống tươi',
  'rau-muống-dong-lanh': 'Rau muống đông lạnh',
  'rau-muống-hữu-co': 'Rau muống hữu cơ',
  'rau-mồng-toi-tuoi': 'Rau mồng tơi tươi',
  'rau-mồng-toi-dong-lanh': 'Rau mồng tơi đông lạnh',
  'rau-mồng-toi-hữu-co': 'Rau mồng tơi hữu cơ',
  'xa-lach-tuoi': 'Xà lách tươi',
  'xa-lach-dong-lanh': 'Xà lách đông lạnh',
  'xa-lach-hữu-co': 'Xà lách hữu cơ',
  'dua-leo-tuoi': 'Dưa leo tươi',
  'dua-leo-dong-lanh': 'Dưa leo đông lạnh',
  'dua-leo-hữu-co': 'Dưa leo hữu cơ',
  'ca-chua-tuoi': 'Cà chua tươi',
  'ca-chua-dong-lanh': 'Cà chua đông lạnh',
  'ca-chua-hữu-co': 'Cà chua hữu cơ',
  'khổ-qua-tuoi': 'Khổ qua tươi',
  'khổ-qua-dong-lanh': 'Khổ qua đông lạnh',
  'khổ-qua-hữu-co': 'Khổ qua hữu cơ',
  'dậu-que-tuoi': 'Đậu que tươi',
  'dậu-que-dong-lanh': 'Đậu que đông lạnh',
  'dậu-que-hữu-co': 'Đậu que hữu cơ',
  'bắp-ngo-tuoi': 'Bắp ngô tươi',
  'bắp-ngo-dong-lanh': 'Bắp ngô đông lạnh',
  'bắp-ngo-hữu-co': 'Bắp ngô hữu cơ',
  'mang-tuoi': 'Măng tươi',
  'mang-dong-lanh': 'Măng đông lạnh',
  'mang-hữu-co': 'Măng hữu cơ',
  'ca-tim': 'Cà tím',
  'ca-tim-tuoi': 'Cà tím tươi',
  'ca-tim-dong-lanh': 'Cà tím đông lạnh',
  'ca-tim-hữu-co': 'Cà tím hữu cơ',
  'ớt-chuong-do': 'Ớt chuông đỏ',
  'ớt-chuong-do-tuoi': 'Ớt chuông đỏ tươi',
  'ớt-chuong-do-dong-lanh': 'Ớt chuông đỏ đông lạnh',
  'ớt-chuong-do-hữu-co': 'Ớt chuông đỏ hữu cơ',
  'ớt-chuong-xanh': 'Ớt chuông xanh',
  'ớt-chuong-xanh-tuoi': 'Ớt chuông xanh tươi',
  'ớt-chuong-xanh-dong-lanh': 'Ớt chuông xanh đông lạnh',
  'ớt-chuong-xanh-hữu-co': 'Ớt chuông xanh hữu cơ',
  'ớt-chuong-vang': 'Ớt chuông vàng',
  'ớt-chuong-vang-tuoi': 'Ớt chuông vàng tươi',
  'ớt-chuong-vang-dong-lanh': 'Ớt chuông vàng đông lạnh',
  'ớt-chuong-vang-hữu-co': 'Ớt chuông vàng hữu cơ',
  'nấm-rom-tuoi': 'Nấm rơm tươi',
  'nấm-rom-dong-lanh': 'Nấm rơm đông lạnh',
  'nấm-rom-hữu-co': 'Nấm rơm hữu cơ',
  'nấm-bao-ngu-tuoi': 'Nấm bào ngư tươi',
  'nấm-bao-ngu-dong-lanh': 'Nấm bào ngư đông lạnh',
  'nấm-bao-ngu-hữu-co': 'Nấm bào ngư hữu cơ',
  'nấm-kim-cham-tuoi': 'Nấm kim châm tươi',
  'nấm-kim-cham-dong-lanh': 'Nấm kim châm đông lạnh',
  'nấm-kim-cham-hữu-co': 'Nấm kim châm hữu cơ',
  'nấm-dong-co-tuoi': 'Nấm đông cô tươi',
  'nấm-dong-co-dong-lanh': 'Nấm đông cô đông lạnh',
  'nấm-dong-co-hữu-co': 'Nấm đông cô hữu cơ',
  'nấm-huong-tuoi': 'Nấm hương tươi',
  'nấm-huong-dong-lanh': 'Nấm hương đông lạnh',
  'nấm-huong-hữu-co': 'Nấm hương hữu cơ',
  'nấm-mỡ': 'Nấm mỡ',
  'nấm-mỡ-tuoi': 'Nấm mỡ tươi',
  'nấm-mỡ-dong-lanh': 'Nấm mỡ đông lạnh',
  'nấm-mỡ-hữu-co': 'Nấm mỡ hữu cơ',
  'nấm-tuyết': 'Nấm tuyết',
  'nấm-tuyết-tuoi': 'Nấm tuyết tươi',
  'nấm-tuyết-dong-lanh': 'Nấm tuyết đông lạnh',
  'nấm-tuyết-hữu-co': 'Nấm tuyết hữu cơ',
  'dậu-hu-tuoi': 'Đậu hũ tươi',
  'dậu-hu-dong-lanh': 'Đậu hũ đông lạnh',
  'dậu-hu-hữu-co': 'Đậu hũ hữu cơ',
  'dậu-hu-non-tuoi': 'Đậu hũ non tươi',
  'dậu-hu-non-dong-lanh': 'Đậu hũ non đông lạnh',
  'dậu-hu-non-hữu-co': 'Đậu hũ non hữu cơ',
  'tau-hu-ky-tuoi': 'Tàu hũ ky tươi',
  'tau-hu-ky-dong-lanh': 'Tàu hũ ky đông lạnh',
  'tau-hu-ky-hữu-co': 'Tàu hũ ky hữu cơ',
  'dậu-xanh-tuoi': 'Đậu xanh tươi',
  'dậu-xanh-dong-lanh': 'Đậu xanh đông lạnh',
  'dậu-xanh-hữu-co': 'Đậu xanh hữu cơ',
  'dậu-do-tuoi': 'Đậu đỏ tươi',
  'dậu-do-dong-lanh': 'Đậu đỏ đông lạnh',
  'dậu-do-hữu-co': 'Đậu đỏ hữu cơ',
  'dậu-den-tuoi': 'Đậu đen tươi',
  'dậu-den-dong-lanh': 'Đậu đen đông lạnh',
  'dậu-den-hữu-co': 'Đậu đen hữu cơ',
  'dậu-phộng-tuoi': 'Đậu phộng tươi',
  'dậu-phộng-dong-lanh': 'Đậu phộng đông lạnh',
  'dậu-phộng-hữu-co': 'Đậu phộng hữu cơ',
  'dậu-ga': 'Đậu gà',
  'dậu-ga-tuoi': 'Đậu gà tươi',
  'dậu-ga-dong-lanh': 'Đậu gà đông lạnh',
  'dậu-ga-hữu-co': 'Đậu gà hữu cơ',
  'bun-dong-lanh': 'Bún đông lạnh',
  'bun-hữu-co': 'Bún hữu cơ',
  'phở-tuoi': 'Phở tươi',
  'phở-dong-lanh': 'Phở đông lạnh',
  'phở-hữu-co': 'Phở hữu cơ',
  'mi-tuoi': 'Mì tươi',
  'mi-dong-lanh': 'Mì đông lạnh',
  'mi-hữu-co': 'Mì hữu cơ',
  'miến-tuoi': 'Miến tươi',
  'miến-dong-lanh': 'Miến đông lạnh',
  'miến-hữu-co': 'Miến hữu cơ',
  'hu-tiếu-tuoi': 'Hủ tiếu tươi',
  'hu-tiếu-dong-lanh': 'Hủ tiếu đông lạnh',
  'hu-tiếu-hữu-co': 'Hủ tiếu hữu cơ',
  'banh-canh-tuoi': 'Bánh canh tươi',
  'banh-canh-dong-lanh': 'Bánh canh đông lạnh',
  'banh-canh-hữu-co': 'Bánh canh hữu cơ',
  'bun-tuoi-tuoi': 'Bún tươi tươi',
  'bun-tuoi-dong-lanh': 'Bún tươi đông lạnh',
  'bun-tuoi-hữu-co': 'Bún tươi hữu cơ',
  'gao-tuoi': 'Gạo tươi',
  'gao-dong-lanh': 'Gạo đông lạnh',
  'gao-hữu-co': 'Gạo hữu cơ',
  'com-tuoi': 'Cơm tươi',
  'com-dong-lanh': 'Cơm đông lạnh',
  'com-hữu-co': 'Cơm hữu cơ',
  'banh-mi-tuoi': 'Bánh mì tươi',
  'banh-mi-dong-lanh': 'Bánh mì đông lạnh',
  'banh-mi-hữu-co': 'Bánh mì hữu cơ',
  'bột-mi': 'Bột mì',
  'bột-mi-tuoi': 'Bột mì tươi',
  'bột-mi-dong-lanh': 'Bột mì đông lạnh',
  'bột-mi-hữu-co': 'Bột mì hữu cơ',
  'bột-nang': 'Bột năng',
  'bột-nang-tuoi': 'Bột năng tươi',
  'bột-nang-dong-lanh': 'Bột năng đông lạnh',
  'bột-nang-hữu-co': 'Bột năng hữu cơ',
  'bột-bắp': 'Bột bắp',
  'bột-bắp-tuoi': 'Bột bắp tươi',
  'bột-bắp-dong-lanh': 'Bột bắp đông lạnh',
  'bột-bắp-hữu-co': 'Bột bắp hữu cơ',
  'bột-gao': 'Bột gạo',
  'bột-gao-tuoi': 'Bột gạo tươi',
  'bột-gao-dong-lanh': 'Bột gạo đông lạnh',
  'bột-gao-hữu-co': 'Bột gạo hữu cơ',
  'bột-nếp': 'Bột nếp',
  'bột-nếp-tuoi': 'Bột nếp tươi',
  'bột-nếp-dong-lanh': 'Bột nếp đông lạnh',
  'bột-nếp-hữu-co': 'Bột nếp hữu cơ',
  'muối-tuoi': 'Muối tươi',
  'muối-dong-lanh': 'Muối đông lạnh',
  'muối-hữu-co': 'Muối hữu cơ',
  'duờng-tuoi': 'Đường tươi',
  'duờng-dong-lanh': 'Đường đông lạnh',
  'duờng-hữu-co': 'Đường hữu cơ',
  'tieu-tuoi': 'Tiêu tươi',
  'tieu-dong-lanh': 'Tiêu đông lạnh',
  'tieu-hữu-co': 'Tiêu hữu cơ',
  'nuớc-mắm-tuoi': 'Nước mắm tươi',
  'nuớc-mắm-dong-lanh': 'Nước mắm đông lạnh',
  'nuớc-mắm-hữu-co': 'Nước mắm hữu cơ',
  'nuớc-tuong-tuoi': 'Nước tương tươi',
  'nuớc-tuong-dong-lanh': 'Nước tương đông lạnh',
  'nuớc-tuong-hữu-co': 'Nước tương hữu cơ',
  'dầu-an-tuoi': 'Dầu ăn tươi',
  'dầu-an-dong-lanh': 'Dầu ăn đông lạnh',
  'dầu-an-hữu-co': 'Dầu ăn hữu cơ',
  'dầu-hao-tuoi': 'Dầu hào tươi',
  'dầu-hao-dong-lanh': 'Dầu hào đông lạnh',
  'dầu-hao-hữu-co': 'Dầu hào hữu cơ',
  'tuong-ớt-tuoi': 'Tương ớt tươi',
  'tuong-ớt-dong-lanh': 'Tương ớt đông lạnh',
  'tuong-ớt-hữu-co': 'Tương ớt hữu cơ',
  'tuong-ca-tuoi': 'Tương cà tươi',
  'tuong-ca-dong-lanh': 'Tương cà đông lạnh',
  'tuong-ca-hữu-co': 'Tương cà hữu cơ',
  'mắm-ruốc-tuoi': 'Mắm ruốc tươi',
  'mắm-ruốc-dong-lanh': 'Mắm ruốc đông lạnh',
  'mắm-ruốc-hữu-co': 'Mắm ruốc hữu cơ',
  'mắm-tom-tuoi': 'Mắm tôm tươi',
  'mắm-tom-dong-lanh': 'Mắm tôm đông lạnh',
  'mắm-tom-hữu-co': 'Mắm tôm hữu cơ',
  'hat-nem': 'Hạt nêm',
  'hat-nem-tuoi': 'Hạt nêm tươi',
  'hat-nem-dong-lanh': 'Hạt nêm đông lạnh',
  'hat-nem-hữu-co': 'Hạt nêm hữu cơ',
  'bột-ngot': 'Bột ngọt',
  'bột-ngot-tuoi': 'Bột ngọt tươi',
  'bột-ngot-dong-lanh': 'Bột ngọt đông lạnh',
  'bột-ngot-hữu-co': 'Bột ngọt hữu cơ',
  'sa-tế': 'Sa tế',
  'sa-tế-tuoi': 'Sa tế tươi',
  'sa-tế-dong-lanh': 'Sa tế đông lạnh',
  'sa-tế-hữu-co': 'Sa tế hữu cơ',
  'hanh-la-tuoi': 'Hành lá tươi',
  'hanh-la-dong-lanh': 'Hành lá đông lạnh',
  'hanh-la-hữu-co': 'Hành lá hữu cơ',
  'hanh-tim-tuoi': 'Hành tím tươi',
  'hanh-tim-dong-lanh': 'Hành tím đông lạnh',
  'hanh-tim-hữu-co': 'Hành tím hữu cơ',
  'toi-tuoi': 'Tỏi tươi',
  'toi-dong-lanh': 'Tỏi đông lạnh',
  'toi-hữu-co': 'Tỏi hữu cơ',
  'gừng-tuoi': 'Gừng tươi',
  'gừng-dong-lanh': 'Gừng đông lạnh',
  'gừng-hữu-co': 'Gừng hữu cơ',
  'sa-tuoi': 'Sả tươi',
  'sa-dong-lanh': 'Sả đông lạnh',
  'sa-hữu-co': 'Sả hữu cơ',
  'ớt-tuoi': 'Ớt tươi',
  'ớt-dong-lanh': 'Ớt đông lạnh',
  'ớt-hữu-co': 'Ớt hữu cơ',
  'ngo-ri-tuoi': 'Ngò rí tươi',
  'ngo-ri-dong-lanh': 'Ngò rí đông lạnh',
  'ngo-ri-hữu-co': 'Ngò rí hữu cơ',
  'rau-ram-tuoi': 'Rau răm tươi',
  'rau-ram-dong-lanh': 'Rau răm đông lạnh',
  'rau-ram-hữu-co': 'Rau răm hữu cơ',
  'hung-quế-tuoi': 'Húng quế tươi',
  'hung-quế-dong-lanh': 'Húng quế đông lạnh',
  'hung-quế-hữu-co': 'Húng quế hữu cơ',
  'tia-to-tuoi': 'Tía tô tươi',
  'tia-to-dong-lanh': 'Tía tô đông lạnh',
  'tia-to-hữu-co': 'Tía tô hữu cơ',
  'la-chanh': 'Lá chanh',
  'la-chanh-tuoi': 'Lá chanh tươi',
  'la-chanh-dong-lanh': 'Lá chanh đông lạnh',
  'la-chanh-hữu-co': 'Lá chanh hữu cơ',
  'trứng-ga-tuoi': 'Trứng gà tươi',
  'trứng-ga-dong-lanh': 'Trứng gà đông lạnh',
  'trứng-ga-hữu-co': 'Trứng gà hữu cơ',
  'trứng-vit-tuoi': 'Trứng vịt tươi',
  'trứng-vit-dong-lanh': 'Trứng vịt đông lạnh',
  'trứng-vit-hữu-co': 'Trứng vịt hữu cơ',
  'trứng-cut-tuoi': 'Trứng cút tươi',
  'trứng-cut-dong-lanh': 'Trứng cút đông lạnh',
  'trứng-cut-hữu-co': 'Trứng cút hữu cơ',
  'trứng-muối': 'Trứng muối',
  'trứng-muối-tuoi': 'Trứng muối tươi',
  'trứng-muối-dong-lanh': 'Trứng muối đông lạnh',
  'trứng-muối-hữu-co': 'Trứng muối hữu cơ',
  'trứng-bắc-thao': 'Trứng bắc thảo',
  'trứng-bắc-thao-tuoi': 'Trứng bắc thảo tươi',
  'trứng-bắc-thao-dong-lanh': 'Trứng bắc thảo đông lạnh',
  'trứng-bắc-thao-hữu-co': 'Trứng bắc thảo hữu cơ',
  'cha-ca-tuoi': 'Chả cá tươi',
  'cha-ca-dong-lanh': 'Chả cá đông lạnh',
  'cha-ca-hữu-co': 'Chả cá hữu cơ',
  'cha-lua-tuoi': 'Chả lụa tươi',
  'cha-lua-dong-lanh': 'Chả lụa đông lạnh',
  'cha-lua-hữu-co': 'Chả lụa hữu cơ',
  'xuc-xich-tuoi': 'Xúc xích tươi',
  'xuc-xich-dong-lanh': 'Xúc xích đông lạnh',
  'xuc-xich-hữu-co': 'Xúc xích hữu cơ',
  'thit-vien-tuoi': 'Thịt viên tươi',
  'thit-vien-dong-lanh': 'Thịt viên đông lạnh',
  'thit-vien-hữu-co': 'Thịt viên hữu cơ',
  'gio-sống-tuoi': 'Giò sống tươi',
  'gio-sống-dong-lanh': 'Giò sống đông lạnh',
  'gio-sống-hữu-co': 'Giò sống hữu cơ',
  'nem-chua-tuoi': 'Nem chua tươi',
  'nem-chua-dong-lanh': 'Nem chua đông lạnh',
  'nem-chua-hữu-co': 'Nem chua hữu cơ',
  'lap-xuởng-tuoi': 'Lạp xưởng tươi',
  'lap-xuởng-dong-lanh': 'Lạp xưởng đông lạnh',
  'lap-xuởng-hữu-co': 'Lạp xưởng hữu cơ',
  pate: 'Pate',
  'pate-tuoi': 'Pate tươi',
  'pate-dong-lanh': 'Pate đông lạnh',
  'pate-hữu-co': 'Pate hữu cơ',
  'canh-khoai-mo-tim': 'Canh Khoai Mỡ Tím',
  'hu-tieu-xao-chay-pad-thai-chay': 'Hủ Tiếu Xào Chay (Pad Thai Chay)',
  'dua-leo-dua-chuot': 'Dưa leo (Dưa chuột)',
  'rong-bien': 'Rong biển',
  'khom-hay-dua-thom': 'Khóm (hay dứa, thơm)',
  'khoai-mo': 'Khoai mỡ',
  'sau-rieng': 'Sầu riêng',
  'cam-vang': 'Cam Vàng',
  'dau-tay': 'Dâu tây',
  'viet-quat': 'Việt quất',
  'mam-xoi': 'Mâm xôi',
  'soda-mix-mixed-berries': 'Soda Mix Mixed Berries',
  'mit-thai': 'Mít thái',
  chuoi: 'Chuối',
  'trung-bac-thao': 'Trứng Bắc Thảo',
  'pho-mai': 'Phô mai',
  'hat-dieu': 'Hạt điều',
  'sua-dac': 'Sữa đặc',
  'sua-tuoi': 'Sữa tươi',
  'siro-trai-cay': 'Siro trái cây',
  'chanh-day': 'Chanh dây',
  'banh-trang-cuon': 'Bánh tráng cuốn',
  tra: 'Trà',
  'socola-thanh-pham': 'Socola (Thành phẩm)',
  cacao: 'Cacao',
  'tao-do': 'Táo đỏ',
  'tao-xanh': 'Táo xanh',
  'mi-y': 'Mì ý',
  'banh-pho': 'Bánh phở',
  'bap-cai-tim': 'Bắp cải tím',
  'bap-cai-trang': 'Bắp cải trắng',
  'dau-den': 'Đậu đen',
  'dau-trang': 'Đậu trắng',
  'dau-ha-lan': 'Đậu hà lan',
  'cha-lua-chay': 'Chả lụa chay',
  'hat-chia': 'Hạt chia',
  'hat-sen': 'Hạt sen',
  'banh-mi': 'Bánh mì',
  mayonnaise: 'Mayonnaise',
  'dau-rong': 'Đậu rồng'
};

export default tags;
