const tags: Record<string, string> = {
  "gioi-thieu": "Giới thiệu",
  "gio-hang": "Giỏ hàng",
  "thong-tin": "Thông tin cá nhân",
  "thuc-don": "Thực đơn",
  "goi-mon": "Gọi món",
  "khuyen-mai": "Khuyến mãi",
  "lien-he": "Liên hệ",
  "goi-mon-nhanh": "Mua hàng nhanh",
  "thanh-toan": "Thanh toán",
  "tin-tuc": "Tin tức",
  "dang-nhap": "Đăng nhập",
  "dang-ki": "Đăng kí",
  "san-pham": "Sản phẩm",
  "yeu-thich": "Yêu thích",
  "danh-gia": "Đánh giá",
  "thit-tuoi": "Thịt tươi",
  "san-pham-moi": "Sản phẩm mới",
  "san-pham-hot": "Sản phẩm nổi bật",
  "san-pham-promotion": "Sản phẩm khuyến mãi",
  "san-pham-ban-chay": "Sản phẩm bán chạy",
  "thuc-uong": "Thức uống",
  "don-hang-cua-toi": "Đơn hàng của tôi",
  "com-tam-suon-bi-cha": "Cơm tấm sườn bì chả",
  "canh-rong-bien-dau-hu-non": "Canh rong biển đậu hũ non",
  "chuoi-nuong-nuoc-cot-dua": "Chuối nướng nước cốt dừa",
  "banh-da-lon": "Bánh da lợn",
  "banh-flan-caramel": "Bánh flan caramel",
  "bun-bo-hue": "Bún bò Huế",
  "banh-trang-nuong": "Bánh tráng nướng",
  "thuy-linh-xinh": "Thùy Linh Xinh",
  "xoi-bap": "Xôi bắp (ngô)",
  "xoi-dau-phong": "Xôi đậu phộng",
  "xoi-man": "Xôi mặn",
  "xoi-ngot-la-dua": "Xôi ngọt lá dứa",
  "xoi-xoai": "Xôi xoài",
  "banh-trang-cha-bong": "Bánh tráng chà bông",
  "banh-trang-tron": "Bánh tráng trộn",
  "banh-trang-tac": "Bánh tráng tắc",
  "banh-trang-cuon-sot-me": "Bánh tráng cuốn sốt me",
  "pho-bo": "Phở bò",
  "che-ba-mau": "Chè ba màu",
  "nuoc-mia": "Nước mía",
  "nuoc-ep-cam-tuoi": "Nước ép cam tươi",
  "ca-phe-sua-da": "Cà phê sữa đá",
  "bo-kho-chay": "Bò kho chay",
  "banh-cuon": "Bánh cuốn",
  "bun-cha-ha-noi": "Bún chả Hà Nội",
  "chao-ga-xe-phay": "Cháo gà xé phay",
  "bun-thai-chay": "Bún Thái chay",
  "com-chay-thap-cam": "Cơm chay thập cẩm",
  "mon-chinh": "Món chính",
  "mon-chay": "Món chay",
  "com": "Cơm",
  "rau-cu": "Rau củ",
  "thanh-toan-vnpay": "Thanh toán VnPay",
  "giam-gia-15": "Giảm giá 15%",
  "giam-50": "Giảm 50%",
  "giam-100k": "Giảm 100k",
  "do-uong": "Đồ uống",
  "an-vat-trang-mieng": "Ăn vặt & tráng miệng",
  "bun": "Bún",
  "do-xao": "Đồ xào",
  "mon-nuoc": "Món nước",
  "mon-nuong": "Món nướng",
  "ca-phe": "Cà phê",
  "nuoc-giai-khat": "Nước giải khát",
  "tra-sua": "Trà sữa",
  "banh-trang": "Bánh tráng",
  "banh-man": "Bánh mặn",
  "banh-ngot": "Bánh ngọt",
  "thit-bo": "Thịt bò",
  "thit-ga": "Thịt gà",
  "thit-heo": "Thịt heo",
  "tom": "Tôm",
  "muc": "Mực",
  "ca-cac-loai": "Cá các loại",
  "cac-loai-oc": "Các loại ốc",
  "cu-cai-trang": "Củ cải trắng",
  "ca-rot": "Cà rốt",
  "cai-thia": "Cải thìa",
  "bong-cai": "Bông cải",
  "nam-meo": "Nấm mèo",
  "nam-kim-cham": "Nấm kim châm",
  "nam-moc-nhi": "Nấm mộc nhỉ",
  "nam-dui-ga": "Nấm đùi gà",
  "dau-hu-tuoi": "Đậu hủ tươi",
  "dau-hu-chien": "Đậu hủ chiên",
  "dau-hu-ki": "Đậu hủ ki",
  "cha-chay": "Chả chay",
  "dua-leo": "Dưa leo",
  "ca-chua": "Cà chua",
  "gia-do": "Giá đỗ",
  "rau-xa-lach": "Rau xà lách",
  "rau-ma": "Rau má",
  "hoa-chuoi-bap-chuoi": "Hoa chuối (bắp chuối)",
  "rau-thom-hung-que-hung-lang": "Rau thơm húng quế - húng láng",
  "rau-muong": "Rau muống",
  "hanh-tay": "Hành tây",
  "ngo-gai": "Ngò gai",
  "hanh-la": "Hành lá",
  "danh-muc-123": "Danh mục 123",
  "danh-muc-1": "Danh mục 1",
  "da1": "Da1"
};

export default tags;