const tags: Record<string, string> = {
  'gioi-thieu': 'Giới thiệu',
  'gio-hang': 'Giỏ hàng',
  'thong-tin': 'Thông tin cá nhân',
  'thuc-don': 'Thực đơn',
  'goi-mon': 'Gọi món',
  'khuyen-mai': 'Khuyến mãi',
  'lien-he': 'Liên hệ',
  'goi-mon-nhanh': 'Mua hàng nhanh',
  'thanh-toan': 'Thanh toán',
  'tin-tuc': 'Tin tức',
  'dang-nhap': 'Đăng nhập',
  'dang-ki': 'Đăng kí',
  'san-pham': 'Sản phẩm',
  'yeu-thich': 'Yêu thích',
  'danh-gia': 'Đánh giá',
  'mon-chay': 'Món chay',
  'an-vat-trang-mieng': 'Ăn vặt tráng miệng',
  'do-uong': 'Đồ uống',
  'mon-khai-vi': 'Món khai vị',
  'mon-chinh': 'Món chính',
  'com-chay': 'Cơm chay',
  'mon-nuoc-chay': 'Món nước chay',
  'mon-kho': 'Món kho',
  'rau-cu': 'Rau củ',
  'banh-ngot': 'Bánh ngọt',
  che: 'Chè',
  kem: 'Kem',
  khoai: 'Khoai',
  'banh-trang': 'Bánh tráng',
  'trai-cay': 'Trái cây',
  xoi: 'Xôi',
  'nuoc-giai-khat': 'Nước giải khát',
  'ca-phe': 'Cà phê',
  'tra-sua': 'Trà sữa',
  'sinh-to': 'Sinh tố',
  'nuoc-ep': 'Nước ép',
  nem: 'Nem',
  salad: 'Salad',
  'banh-man': 'Bánh mặn',
  sup: 'Súp',
  com: 'Cơm',
  'mon-nuoc': 'Món nước',
  'mon-chien-xao': 'Món chiên xào',
  'mon-nuong': 'Món nướng',
  'san-pham-moi': 'Sản phẩm mới',
  'san-pham-hot': 'Sản phẩm nổi bật',
  'san-pham-promotion': 'Sản phẩm khuyến mãi',
  'san-pham-ban-chay': 'Sản phẩm bán chạy',
  'thuc-uong': 'Thức uống',
  'don-hang-cua-toi': 'Đơn hàng của tôi',
  'com-tam-suon-bi-cha': 'Cơm tấm sườn bì chả',
  'canh-rong-bien-dau-hu-non': 'Canh rong biển đậu hũ non',
  'chuoi-nuong-nuoc-cot-dua': 'Chuối nướng nước cốt dừa',
  'banh-da-lon': 'Bánh da lợn',
  'banh-flan-caramel': 'Bánh flan caramel',
  'bun-bo-hue': 'Bún bò Huế',
  'banh-trang-nuong': 'Bánh tráng nướng',
  'thuy-linh-xinh': 'Thùy Linh Xinh',
  'xoi-bap': 'Xôi bắp (ngô)',
  'xoi-dau-phong': 'Xôi đậu phộng',
  'xoi-man': 'Xôi mặn',
  'xoi-ngot-la-dua': 'Xôi ngọt lá dứa',
  'xoi-xoai': 'Xôi xoài',
  'banh-trang-cha-bong': 'Bánh tráng chà bông',
  'banh-trang-tron': 'Bánh tráng trộn',
  'banh-trang-tac': 'Bánh tráng tắc',
  'banh-trang-cuon-sot-me': 'Bánh tráng cuốn sốt me',
  'pho-bo': 'Phở bò',
  'che-ba-mau': 'Chè ba màu',
  'nuoc-mia': 'Nước mía',
  'nuoc-ep-cam-tuoi': 'Nước ép cam tươi',
  'ca-phe-sua-da': 'Cà phê sữa đá',
  'bo-kho-chay': 'Bò kho chay',
  'banh-cuon': 'Bánh cuốn',
  'bun-cha-ha-noi': 'Bún chả Hà Nội',
  'chao-ga-xe-phay': 'Cháo gà xé phay',
  'bun-thai-chay': 'Bún Thái chay',
  'com-chay-thap-cam': 'Cơm chay thập cẩm'
};

export default tags;
