const tags: Record<string, string> = {
  'gioi-thieu': 'Giới thiệu',
  'gio-hang': 'Giỏ hàng',
  'thong-tin': 'Thông tin cá nhân',
  'thuc-don': 'Thực đơn',
  'goi-mon': 'Gọi món',
  'khuyen-mai': 'Khuyến mãi',
  'lien-he': 'Liên hệ',
  'goi-mon-nhanh': 'Mua hàng nhanh',
  'thanh-toan': 'Thanh toán',
  'tin-tuc': 'Tin tức',
  'dang-nhap': 'Đăng nhập',
  'dang-ki': 'Đăng kí',
  'san-pham': 'Sản phẩm',
  'yeu-thich': 'Yêu thích',
  'danh-gia': 'Đánh giá',

  'mon-chay': 'Món chay',
  'an-vat-trang-mieng': 'Ăn vặt tráng miệng',
  'do-uong': 'Đồ uống',
  'mon-khai-vi': 'Món khai vị',
  'mon-chinh': 'Món chính',
  'com-chay': 'Cơm chay',
  'mon-nuoc-chay': 'Món nước chay',
  'mon-kho': 'Món kho',
  'rau-cu': 'Rau củ',
  'banh-ngot': 'Bánh ngọt',

  che: 'Chè',
  kem: 'Kem',
  khoai: 'Khoai',
  'banh-trang': 'Bánh tráng',
  'trai-cay': 'Trái cây',
  xoi: 'Xôi',
  'nuoc-giai-khat': 'Nước giải khát',
  'ca-phe': 'Cà phê',
  'tra-sua': 'Trà sữa',
  'sinh-to': 'Sinh tố',
  'nuoc-ep': 'Nước ép',
  nem: 'Nem',
  salad: 'Salad',
  'banh-man': 'Bánh mặn',
  sup: 'Súp',
  com: 'Cơm',
  'mon-nuoc': 'Món nước',
  'mon-chien-xao': 'Món chiên xào',
  'mon-nuong': 'Món nướng',

  'san-pham-moi': 'Sản phẩm mới',
  'san-pham-hot': 'Sản phẩm nổi bật',
  'san-pham-promotion': 'Sản phẩm khuyến mãi',
  'san-pham-ban-chay': 'Sản phẩm bán chạy',
  'thuc-uong': 'Thức uống',

  'don-hang-cua-toi': 'Đơn hàng của tôi'
};

export default tags;
