export function findRole() {}
export function getAllRole() {}
export function getOneRole() {}
export function getOnePermission() {}
export function createRole() {}
export function createManyRole() {}
export function updateRole() {}
export function deleteRole() {}
export function findPermission() {}
export function createPermission() {}
export function createManyPermission() {}
export function updatePermission() {}
export function deletePermission() {}
export function getAllPermission() {}
export function updateUserPermissions() {}
